image: golang:1.13

variables:
  PACKAGE_PATH: /go/src/rgs-core-v2
  CI: ci

stages:
#  - dep
  - test

test:
  stage: test
  script: make test

build:
  image: docker:17
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - docker login -u "${MVRK_OPS_HARBOR_USER}"  -p "${MVRK_OPS_HARBOR_PWD}" "${MVRK_OPS_HARBOR_URI}"
  stage: build
  variables:
    BUILDVERSION: ${CI_COMMIT_SHORT_SHA}
  script:
    - make build
    - make push
    - make latest

#deploy_dev:
#  image: harbor.maverick-ops.com/base/kubernetes-cli:latest
#  stage: deploy
#  only: [master]
#  environment:
#    name: dev
#  before_script:
#    - mkdir ~/.kube
#    - echo "${K8S_CFG_DEV}" > ~/.kube/config
#    - kubectl version --insecure-skip-tls-verify=true
#    - cd deployment/dev
#  script:
#    - |
#      echo "Deploying Dev"
#      echo '--------------------'
#      echo 'Deploy RGS'
#      echo '--------------------'
#      sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
#      sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kustomization.yaml
#      kustomize build . | kubectl --insecure-skip-tls-verify=true  diff -f - || true
#      kustomize build . | kubectl --insecure-skip-tls-verify=true  apply -f -

#deploy_stg:
#  image: harbor.maverick-ops.com/base/kubernetes-cli:latest
#  stage: deploy
#  only: [master]
#  when: manual
#  environment:
#    name: staging
#  before_script:
#    - mkdir ~/.kube
#    - echo "${K8S_CFG_STAGING}" > ~/.kube/config
#    - kubectl version --insecure-skip-tls-verify=true
#    - cd deployment/dev
#  script:
#    - |
#      echo "Deploying Stg"
#      echo '--------------------'
#      echo 'Deploy RGS'
#      echo '--------------------'
#      sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
#      sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kustomization.yaml
#      kustomize build . | kubectl --insecure-skip-tls-verify=true  diff -f - || true
#      kustomize build . | kubectl --insecure-skip-tls-verify=true  apply -f -

#
#deploy_prod:
#  image: harbor.maverick-ops.com/base/kubernetes-cli:latest
#  stage: deploy
#  only: [master]
#  when: manual
#  environment:
#    name: production
#  before_script:
#    - mkdir ~/.kube
#    - echo "${K8S_CFG_PRODUCTION}" > ~/.kube/config
#    - kubectl version --insecure-skip-tls-verify=true
#    - cd deployment/stg
#  script:
#    - |
#      echo "Deploying Stg"
#      echo '--------------------'
#      echo 'Deploy RGS'
#      echo '--------------------'
#      sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
#      sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kustomization.yaml
#      kustomize build . | kubectl --insecure-skip-tls-verify=true  diff -f - || true
#      kustomize build . | kubectl --insecure-skip-tls-verify=true  apply -f -
