---
kind: ConfigMap
apiVersion: v1
metadata:
  name: baseconfigs
  namespace: {{ .Values.namespace | default "elysium" }}
  labels:
  {{- include "rgs-v2.labels" . | nindent 4 }}
data:
  config.yml: |
    # development mode
    devmode: {{ .Values.config.devmode }}
    local: {{ .Values.config.local }}

    # Log levels
    # debug, info, warn, error, fatal
    logging: {{ .Values.config.logging }}
    environment: {{ .Values.config.environment }}


    # mcrouter address
    mcrouter: {{ .Values.config.mcrouter }}

    # server configuration
    server:
      host: {{ .Values.config.server.host }}
      port: {{ .Values.config.server.port }}
      name: {{ .Values.config.server.name }}
    
    sentryDsn: "https://9e9385a737394a4ead1619bc53bcce81@o422612.ingest.sentry.io/5351538"

    # dashur configuration
    dashurconf:
      storeurl: {{ .Values.config.storeurl }}
      storeappid: {{ .Values.config.storeappid }}
      storeapppass: {{ .Values.config.storeapppass }}

    defaultlanguage: {{ .Values.config.defaultlanguage }}
    defaultplatform: {{ .Values.config.defaultplatform }}

    demotokenprefix: {{ .Values.config.demotokenprefix }}
    democurrency: {{ .Values.config.democurrency }}
    datalimit: {{ .Values.config.datalimit }}
    localdatattl: {{ .Values.config.localdatattl }}
  gameConfig.yml: |
    {{- range $i, $engine := .Values.gameConfig }}
    - engineID: {{ $engine.engineID }}
      games:
      {{- range $i2, $game := $engine.games }}
        - name: {{ $game.name }}
          item: {{ $game.item -}}
      {{- end }}
    {{- end }}
  gamification.yml: |
    {{- range $i, $game := .Values.gamification }}
    {{ $i }}:
      function: {{ $game.function }}
      stages: {{ $game.stages }}
      spinsMin: {{ $game.spinsMin }}
      spinsMax: {{ $game.spinsMax }}
    {{- end }}
  hashes.yml: |
    {{- $files := .Files }}
    {{- $files.Get "hashes.yaml" | nindent 4 }}
