// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datatypes_v1.proto

package engine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ccy int32

const (
	Ccy_DEFAULT Ccy = 0
	Ccy_CNY     Ccy = 1
	Ccy_USD     Ccy = 2
	Ccy_GBP     Ccy = 3
	Ccy_EUR     Ccy = 4
	Ccy_JPY     Ccy = 6
	Ccy_THB     Ccy = 7
	Ccy_MYR     Ccy = 8
	Ccy_VND     Ccy = 9
	Ccy_KRW     Ccy = 10
	Ccy_IDR     Ccy = 11
	Ccy_ZAR     Ccy = 12
	Ccy_XBT     Ccy = 13
	Ccy_TRY     Ccy = 14
	Ccy_AMD     Ccy = 15
	Ccy_NOK     Ccy = 16
	Ccy_SEK     Ccy = 17
	Ccy_RUB     Ccy = 18
	Ccy_KZT     Ccy = 19
	Ccy_MMK     Ccy = 20
	Ccy_MXN     Ccy = 21
	Ccy_BOB     Ccy = 22
	Ccy_PYG     Ccy = 23
	Ccy_PEN     Ccy = 24
	Ccy_CLP     Ccy = 25
	Ccy_UYU     Ccy = 26
	Ccy_CAD     Ccy = 27
	Ccy_AED     Ccy = 28
	Ccy_ALL     Ccy = 29
	Ccy_AOA     Ccy = 30
	Ccy_ARS     Ccy = 31
	Ccy_AUD     Ccy = 32
	Ccy_AZN     Ccy = 33
	Ccy_BAM     Ccy = 34
	Ccy_BDT     Ccy = 35
	Ccy_BGN     Ccy = 36
	Ccy_BHD     Ccy = 37
	Ccy_BND     Ccy = 38
	Ccy_BWP     Ccy = 39
	Ccy_CDF     Ccy = 40
	Ccy_CHF     Ccy = 41
	Ccy_CRC     Ccy = 42
	Ccy_COP     Ccy = 43
	Ccy_CZK     Ccy = 44
	Ccy_DKK     Ccy = 45
	Ccy_DOP     Ccy = 46
	Ccy_EGP     Ccy = 47
	Ccy_GEL     Ccy = 48
	Ccy_GHS     Ccy = 49
	Ccy_GIP     Ccy = 50
	Ccy_GNF     Ccy = 51
	Ccy_GTQ     Ccy = 52
	Ccy_HKD     Ccy = 53
	Ccy_HRK     Ccy = 54
	Ccy_HTG     Ccy = 55
	Ccy_HUF     Ccy = 56
	Ccy_ILS     Ccy = 57
	Ccy_INR     Ccy = 58
	Ccy_IQL     Ccy = 59
	Ccy_IRR     Ccy = 60
	Ccy_ISK     Ccy = 61
	Ccy_JOD     Ccy = 62
	Ccy_KES     Ccy = 63
	Ccy_KWD     Ccy = 64
	Ccy_LBP     Ccy = 65
	Ccy_LSL     Ccy = 66
	Ccy_MAD     Ccy = 67
	Ccy_MBC     Ccy = 68
	Ccy_MKB     Ccy = 69
	Ccy_MWK     Ccy = 70
	Ccy_NAD     Ccy = 71
	Ccy_NGN     Ccy = 72
	Ccy_NZD     Ccy = 73
	Ccy_OMR     Ccy = 74
	Ccy_ZMW     Ccy = 75
	Ccy_PHP     Ccy = 76
	Ccy_PLN     Ccy = 77
	Ccy_XOF     Ccy = 78
	Ccy_QAR     Ccy = 79
	Ccy_RON     Ccy = 80
	Ccy_RSD     Ccy = 81
	Ccy_RWF     Ccy = 82
	Ccy_SAR     Ccy = 83
	Ccy_SGD     Ccy = 84
	Ccy_TMT     Ccy = 85
	Ccy_TND     Ccy = 86
	Ccy_TWD     Ccy = 87
	Ccy_TZS     Ccy = 88
	Ccy_UAH     Ccy = 89
	Ccy_UBC     Ccy = 90
	Ccy_UGX     Ccy = 91
	Ccy_XAF     Ccy = 92
	Ccy_VES     Ccy = 93
)

var Ccy_name = map[int32]string{
	0:  "DEFAULT",
	1:  "CNY",
	2:  "USD",
	3:  "GBP",
	4:  "EUR",
	6:  "JPY",
	7:  "THB",
	8:  "MYR",
	9:  "VND",
	10: "KRW",
	11: "IDR",
	12: "ZAR",
	13: "XBT",
	14: "TRY",
	15: "AMD",
	16: "NOK",
	17: "SEK",
	18: "RUB",
	19: "KZT",
	20: "MMK",
	21: "MXN",
	22: "BOB",
	23: "PYG",
	24: "PEN",
	25: "CLP",
	26: "UYU",
	27: "CAD",
	28: "AED",
	29: "ALL",
	30: "AOA",
	31: "ARS",
	32: "AUD",
	33: "AZN",
	34: "BAM",
	35: "BDT",
	36: "BGN",
	37: "BHD",
	38: "BND",
	39: "BWP",
	40: "CDF",
	41: "CHF",
	42: "CRC",
	43: "COP",
	44: "CZK",
	45: "DKK",
	46: "DOP",
	47: "EGP",
	48: "GEL",
	49: "GHS",
	50: "GIP",
	51: "GNF",
	52: "GTQ",
	53: "HKD",
	54: "HRK",
	55: "HTG",
	56: "HUF",
	57: "ILS",
	58: "INR",
	59: "IQL",
	60: "IRR",
	61: "ISK",
	62: "JOD",
	63: "KES",
	64: "KWD",
	65: "LBP",
	66: "LSL",
	67: "MAD",
	68: "MBC",
	69: "MKB",
	70: "MWK",
	71: "NAD",
	72: "NGN",
	73: "NZD",
	74: "OMR",
	75: "ZMW",
	76: "PHP",
	77: "PLN",
	78: "XOF",
	79: "QAR",
	80: "RON",
	81: "RSD",
	82: "RWF",
	83: "SAR",
	84: "SGD",
	85: "TMT",
	86: "TND",
	87: "TWD",
	88: "TZS",
	89: "UAH",
	90: "UBC",
	91: "UGX",
	92: "XAF",
	93: "VES",
}

var Ccy_value = map[string]int32{
	"DEFAULT": 0,
	"CNY":     1,
	"USD":     2,
	"GBP":     3,
	"EUR":     4,
	"JPY":     6,
	"THB":     7,
	"MYR":     8,
	"VND":     9,
	"KRW":     10,
	"IDR":     11,
	"ZAR":     12,
	"XBT":     13,
	"TRY":     14,
	"AMD":     15,
	"NOK":     16,
	"SEK":     17,
	"RUB":     18,
	"KZT":     19,
	"MMK":     20,
	"MXN":     21,
	"BOB":     22,
	"PYG":     23,
	"PEN":     24,
	"CLP":     25,
	"UYU":     26,
	"CAD":     27,
	"AED":     28,
	"ALL":     29,
	"AOA":     30,
	"ARS":     31,
	"AUD":     32,
	"AZN":     33,
	"BAM":     34,
	"BDT":     35,
	"BGN":     36,
	"BHD":     37,
	"BND":     38,
	"BWP":     39,
	"CDF":     40,
	"CHF":     41,
	"CRC":     42,
	"COP":     43,
	"CZK":     44,
	"DKK":     45,
	"DOP":     46,
	"EGP":     47,
	"GEL":     48,
	"GHS":     49,
	"GIP":     50,
	"GNF":     51,
	"GTQ":     52,
	"HKD":     53,
	"HRK":     54,
	"HTG":     55,
	"HUF":     56,
	"ILS":     57,
	"INR":     58,
	"IQL":     59,
	"IRR":     60,
	"ISK":     61,
	"JOD":     62,
	"KES":     63,
	"KWD":     64,
	"LBP":     65,
	"LSL":     66,
	"MAD":     67,
	"MBC":     68,
	"MKB":     69,
	"MWK":     70,
	"NAD":     71,
	"NGN":     72,
	"NZD":     73,
	"OMR":     74,
	"ZMW":     75,
	"PHP":     76,
	"PLN":     77,
	"XOF":     78,
	"QAR":     79,
	"RON":     80,
	"RSD":     81,
	"RWF":     82,
	"SAR":     83,
	"SGD":     84,
	"TMT":     85,
	"TND":     86,
	"TWD":     87,
	"TZS":     88,
	"UAH":     89,
	"UBC":     90,
	"UGX":     91,
	"XAF":     92,
	"VES":     93,
}

func (x Ccy) String() string {
	return proto.EnumName(Ccy_name, int32(x))
}

func (Ccy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{0}
}

type WalletTransactionPB_Type int32

const (
	WalletTransactionPB_DEFAULT  WalletTransactionPB_Type = 0
	WalletTransactionPB_WAGER    WalletTransactionPB_Type = 1
	WalletTransactionPB_PAYOUT   WalletTransactionPB_Type = 2
	WalletTransactionPB_ENDROUND WalletTransactionPB_Type = 3
)

var WalletTransactionPB_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "WAGER",
	2: "PAYOUT",
	3: "ENDROUND",
}

var WalletTransactionPB_Type_value = map[string]int32{
	"DEFAULT":  0,
	"WAGER":    1,
	"PAYOUT":   2,
	"ENDROUND": 3,
}

func (x WalletTransactionPB_Type) String() string {
	return proto.EnumName(WalletTransactionPB_Type_name, int32(x))
}

func (WalletTransactionPB_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{2, 0}
}

type GamestatePB_GameID int32

const (
	GamestatePB_DEFAULT                 GamestatePB_GameID = 0
	GamestatePB_THE_YEAR_OF_ZHU         GamestatePB_GameID = 1
	GamestatePB_ZODIAC                  GamestatePB_GameID = 2
	GamestatePB_CAT_THIEF               GamestatePB_GameID = 3
	GamestatePB_THREE_KINGDOM_SHU       GamestatePB_GameID = 4
	GamestatePB_THREE_KINGDOM_WEI       GamestatePB_GameID = 5
	GamestatePB_THREE_KINGDOM_WU        GamestatePB_GameID = 6
	GamestatePB_CRIMSON_MASQUERADE      GamestatePB_GameID = 7
	GamestatePB_JUNGLE_SAGA             GamestatePB_GameID = 8
	GamestatePB_CANDY_GIRLS             GamestatePB_GameID = 9
	GamestatePB_WUKONG_TREASURES        GamestatePB_GameID = 10
	GamestatePB_STREET_RACER            GamestatePB_GameID = 11
	GamestatePB_BABAKS_QUEST            GamestatePB_GameID = 12
	GamestatePB_ASTRO_GEMS              GamestatePB_GameID = 13
	GamestatePB_PANDA                   GamestatePB_GameID = 14
	GamestatePB_KING_OF_GAMBLERS        GamestatePB_GameID = 15
	GamestatePB_ART_OF_THE_FIST         GamestatePB_GameID = 16
	GamestatePB_SEASONS_WINTER          GamestatePB_GameID = 17
	GamestatePB_SEASONS_SPRING          GamestatePB_GameID = 18
	GamestatePB_SEASONS_SUMMER          GamestatePB_GameID = 19
	GamestatePB_SEASONS_AUTUMN          GamestatePB_GameID = 20
	GamestatePB_SEASONS                 GamestatePB_GameID = 21
	GamestatePB_FRUITY_VERSE            GamestatePB_GameID = 22
	GamestatePB_A_FAIRY_TALE            GamestatePB_GameID = 23
	GamestatePB_A_HIDDEN_FOREST         GamestatePB_GameID = 24
	GamestatePB_BATTLEMECH              GamestatePB_GameID = 25
	GamestatePB_A_MILLION_LIGHTS        GamestatePB_GameID = 26
	GamestatePB_BISTRO                  GamestatePB_GameID = 27
	GamestatePB_CLOUD9                  GamestatePB_GameID = 28
	GamestatePB_LANTERN_FESTIVAL        GamestatePB_GameID = 29
	GamestatePB_A_CANDY_GIRLS_CHRISTMAS GamestatePB_GameID = 30
	GamestatePB_SKY_JEWELS              GamestatePB_GameID = 31
	GamestatePB_PEARL_FISHER            GamestatePB_GameID = 32
	GamestatePB_GOAL                    GamestatePB_GameID = 33
	GamestatePB_DAYTONA                 GamestatePB_GameID = 34
	GamestatePB_A_YEAR_OF_LAOSHU        GamestatePB_GameID = 35
	GamestatePB_DRAGON_MYST             GamestatePB_GameID = 36
	GamestatePB_COOKOFF_CHAMPION        GamestatePB_GameID = 37
	GamestatePB_CANDY_SMASH             GamestatePB_GameID = 38
	GamestatePB_VALLEY_OF_KINGS         GamestatePB_GameID = 39
	GamestatePB_CRAZY_EASTER_EGGS       GamestatePB_GameID = 40
	GamestatePB_DRIFT                   GamestatePB_GameID = 41
)

var GamestatePB_GameID_name = map[int32]string{
	0:  "DEFAULT",
	1:  "THE_YEAR_OF_ZHU",
	2:  "ZODIAC",
	3:  "CAT_THIEF",
	4:  "THREE_KINGDOM_SHU",
	5:  "THREE_KINGDOM_WEI",
	6:  "THREE_KINGDOM_WU",
	7:  "CRIMSON_MASQUERADE",
	8:  "JUNGLE_SAGA",
	9:  "CANDY_GIRLS",
	10: "WUKONG_TREASURES",
	11: "STREET_RACER",
	12: "BABAKS_QUEST",
	13: "ASTRO_GEMS",
	14: "PANDA",
	15: "KING_OF_GAMBLERS",
	16: "ART_OF_THE_FIST",
	17: "SEASONS_WINTER",
	18: "SEASONS_SPRING",
	19: "SEASONS_SUMMER",
	20: "SEASONS_AUTUMN",
	21: "SEASONS",
	22: "FRUITY_VERSE",
	23: "A_FAIRY_TALE",
	24: "A_HIDDEN_FOREST",
	25: "BATTLEMECH",
	26: "A_MILLION_LIGHTS",
	27: "BISTRO",
	28: "CLOUD9",
	29: "LANTERN_FESTIVAL",
	30: "A_CANDY_GIRLS_CHRISTMAS",
	31: "SKY_JEWELS",
	32: "PEARL_FISHER",
	33: "GOAL",
	34: "DAYTONA",
	35: "A_YEAR_OF_LAOSHU",
	36: "DRAGON_MYST",
	37: "COOKOFF_CHAMPION",
	38: "CANDY_SMASH",
	39: "VALLEY_OF_KINGS",
	40: "CRAZY_EASTER_EGGS",
	41: "DRIFT",
}

var GamestatePB_GameID_value = map[string]int32{
	"DEFAULT":                 0,
	"THE_YEAR_OF_ZHU":         1,
	"ZODIAC":                  2,
	"CAT_THIEF":               3,
	"THREE_KINGDOM_SHU":       4,
	"THREE_KINGDOM_WEI":       5,
	"THREE_KINGDOM_WU":        6,
	"CRIMSON_MASQUERADE":      7,
	"JUNGLE_SAGA":             8,
	"CANDY_GIRLS":             9,
	"WUKONG_TREASURES":        10,
	"STREET_RACER":            11,
	"BABAKS_QUEST":            12,
	"ASTRO_GEMS":              13,
	"PANDA":                   14,
	"KING_OF_GAMBLERS":        15,
	"ART_OF_THE_FIST":         16,
	"SEASONS_WINTER":          17,
	"SEASONS_SPRING":          18,
	"SEASONS_SUMMER":          19,
	"SEASONS_AUTUMN":          20,
	"SEASONS":                 21,
	"FRUITY_VERSE":            22,
	"A_FAIRY_TALE":            23,
	"A_HIDDEN_FOREST":         24,
	"BATTLEMECH":              25,
	"A_MILLION_LIGHTS":        26,
	"BISTRO":                  27,
	"CLOUD9":                  28,
	"LANTERN_FESTIVAL":        29,
	"A_CANDY_GIRLS_CHRISTMAS": 30,
	"SKY_JEWELS":              31,
	"PEARL_FISHER":            32,
	"GOAL":                    33,
	"DAYTONA":                 34,
	"A_YEAR_OF_LAOSHU":        35,
	"DRAGON_MYST":             36,
	"COOKOFF_CHAMPION":        37,
	"CANDY_SMASH":             38,
	"VALLEY_OF_KINGS":         39,
	"CRAZY_EASTER_EGGS":       40,
	"DRIFT":                   41,
}

func (x GamestatePB_GameID) String() string {
	return proto.EnumName(GamestatePB_GameID_name, int32(x))
}

func (GamestatePB_GameID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{3, 0}
}

type GamestatePB_Action int32

const (
	GamestatePB_base       GamestatePB_Action = 0
	GamestatePB_finish     GamestatePB_Action = 1
	GamestatePB_freespin   GamestatePB_Action = 2
	GamestatePB_pickSpins  GamestatePB_Action = 3
	GamestatePB_respin     GamestatePB_Action = 4
	GamestatePB_freespin2  GamestatePB_Action = 5
	GamestatePB_freespin3  GamestatePB_Action = 6
	GamestatePB_freespin4  GamestatePB_Action = 7
	GamestatePB_freespin5  GamestatePB_Action = 8
	GamestatePB_freespin10 GamestatePB_Action = 9
	GamestatePB_freespin25 GamestatePB_Action = 10
	GamestatePB_cascade    GamestatePB_Action = 11
)

var GamestatePB_Action_name = map[int32]string{
	0:  "base",
	1:  "finish",
	2:  "freespin",
	3:  "pickSpins",
	4:  "respin",
	5:  "freespin2",
	6:  "freespin3",
	7:  "freespin4",
	8:  "freespin5",
	9:  "freespin10",
	10: "freespin25",
	11: "cascade",
}

var GamestatePB_Action_value = map[string]int32{
	"base":       0,
	"finish":     1,
	"freespin":   2,
	"pickSpins":  3,
	"respin":     4,
	"freespin2":  5,
	"freespin3":  6,
	"freespin4":  7,
	"freespin5":  8,
	"freespin10": 9,
	"freespin25": 10,
	"cascade":    11,
}

func (x GamestatePB_Action) String() string {
	return proto.EnumName(GamestatePB_Action_name, int32(x))
}

func (GamestatePB_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{3, 1}
}

type PayoutPB struct {
	Symbol               int32    `protobuf:"varint,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Multiplier           int32    `protobuf:"varint,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayoutPB) Reset()         { *m = PayoutPB{} }
func (m *PayoutPB) String() string { return proto.CompactTextString(m) }
func (*PayoutPB) ProtoMessage()    {}
func (*PayoutPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{0}
}

func (m *PayoutPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayoutPB.Unmarshal(m, b)
}
func (m *PayoutPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayoutPB.Marshal(b, m, deterministic)
}
func (m *PayoutPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayoutPB.Merge(m, src)
}
func (m *PayoutPB) XXX_Size() int {
	return xxx_messageInfo_PayoutPB.Size(m)
}
func (m *PayoutPB) XXX_DiscardUnknown() {
	xxx_messageInfo_PayoutPB.DiscardUnknown(m)
}

var xxx_messageInfo_PayoutPB proto.InternalMessageInfo

func (m *PayoutPB) GetSymbol() int32 {
	if m != nil {
		return m.Symbol
	}
	return 0
}

func (m *PayoutPB) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PayoutPB) GetMultiplier() int32 {
	if m != nil {
		return m.Multiplier
	}
	return 0
}

type PrizePB struct {
	Payout               *PayoutPB `protobuf:"bytes,1,opt,name=payout,proto3" json:"payout,omitempty"`
	Multiplier           int32     `protobuf:"varint,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	SymbolPositions      []int32   `protobuf:"varint,3,rep,packed,name=symbol_positions,json=symbolPositions,proto3" json:"symbol_positions,omitempty"`
	Winline              int32     `protobuf:"varint,4,opt,name=winline,proto3" json:"winline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrizePB) Reset()         { *m = PrizePB{} }
func (m *PrizePB) String() string { return proto.CompactTextString(m) }
func (*PrizePB) ProtoMessage()    {}
func (*PrizePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{1}
}

func (m *PrizePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrizePB.Unmarshal(m, b)
}
func (m *PrizePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrizePB.Marshal(b, m, deterministic)
}
func (m *PrizePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrizePB.Merge(m, src)
}
func (m *PrizePB) XXX_Size() int {
	return xxx_messageInfo_PrizePB.Size(m)
}
func (m *PrizePB) XXX_DiscardUnknown() {
	xxx_messageInfo_PrizePB.DiscardUnknown(m)
}

var xxx_messageInfo_PrizePB proto.InternalMessageInfo

func (m *PrizePB) GetPayout() *PayoutPB {
	if m != nil {
		return m.Payout
	}
	return nil
}

func (m *PrizePB) GetMultiplier() int32 {
	if m != nil {
		return m.Multiplier
	}
	return 0
}

func (m *PrizePB) GetSymbolPositions() []int32 {
	if m != nil {
		return m.SymbolPositions
	}
	return nil
}

func (m *PrizePB) GetWinline() int32 {
	if m != nil {
		return m.Winline
	}
	return 0
}

type WalletTransactionPB struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64                    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 WalletTransactionPB_Type `protobuf:"varint,3,opt,name=type,proto3,enum=engine.WalletTransactionPB_Type" json:"type,omitempty"`
	Currency             Ccy                      `protobuf:"varint,4,opt,name=currency,proto3,enum=engine.Ccy" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WalletTransactionPB) Reset()         { *m = WalletTransactionPB{} }
func (m *WalletTransactionPB) String() string { return proto.CompactTextString(m) }
func (*WalletTransactionPB) ProtoMessage()    {}
func (*WalletTransactionPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{2}
}

func (m *WalletTransactionPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletTransactionPB.Unmarshal(m, b)
}
func (m *WalletTransactionPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletTransactionPB.Marshal(b, m, deterministic)
}
func (m *WalletTransactionPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletTransactionPB.Merge(m, src)
}
func (m *WalletTransactionPB) XXX_Size() int {
	return xxx_messageInfo_WalletTransactionPB.Size(m)
}
func (m *WalletTransactionPB) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletTransactionPB.DiscardUnknown(m)
}

var xxx_messageInfo_WalletTransactionPB proto.InternalMessageInfo

func (m *WalletTransactionPB) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WalletTransactionPB) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WalletTransactionPB) GetType() WalletTransactionPB_Type {
	if m != nil {
		return m.Type
	}
	return WalletTransactionPB_DEFAULT
}

func (m *WalletTransactionPB) GetCurrency() Ccy {
	if m != nil {
		return m.Currency
	}
	return Ccy_DEFAULT
}

type GamestatePB struct {
	GameId               GamestatePB_GameID        `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3,enum=engine.GamestatePB_GameID" json:"game_id,omitempty"`
	EngineDef            int32                     `protobuf:"varint,2,opt,name=engine_def,json=engineDef,proto3" json:"engine_def,omitempty"`
	BetPerLine           int64                     `protobuf:"varint,3,opt,name=bet_per_line,json=betPerLine,proto3" json:"bet_per_line,omitempty"`
	Currency             Ccy                       `protobuf:"varint,4,opt,name=currency,proto3,enum=engine.Ccy" json:"currency,omitempty"`
	PreviousGamestate    []byte                    `protobuf:"bytes,5,opt,name=previous_gamestate,json=previousGamestate,proto3" json:"previous_gamestate,omitempty"`
	NextGamestate        []byte                    `protobuf:"bytes,6,opt,name=next_gamestate,json=nextGamestate,proto3" json:"next_gamestate,omitempty"`
	Action               GamestatePB_Action        `protobuf:"varint,7,opt,name=action,proto3,enum=engine.GamestatePB_Action" json:"action,omitempty"`
	SymbolGrid           []*GamestatePB_Reel       `protobuf:"bytes,8,rep,name=symbol_grid,json=symbolGrid,proto3" json:"symbol_grid,omitempty"`
	Prizes               []*PrizePB                `protobuf:"bytes,9,rep,name=prizes,proto3" json:"prizes,omitempty"`
	SelectedWinLines     []int32                   `protobuf:"varint,10,rep,packed,name=selected_win_lines,json=selectedWinLines,proto3" json:"selected_win_lines,omitempty"`
	RelativePayout       int32                     `protobuf:"varint,11,opt,name=relative_payout,json=relativePayout,proto3" json:"relative_payout,omitempty"`
	Multiplier           int32                     `protobuf:"varint,12,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	StopList             []int32                   `protobuf:"varint,13,rep,packed,name=stop_list,json=stopList,proto3" json:"stop_list,omitempty"`
	NextActions          []GamestatePB_Action      `protobuf:"varint,14,rep,packed,name=next_actions,json=nextActions,proto3,enum=engine.GamestatePB_Action" json:"next_actions,omitempty"`
	Gamification         *GamestatePB_Gamification `protobuf:"bytes,15,opt,name=gamification,proto3" json:"gamification,omitempty"`
	CumulativeWin        int64                     `protobuf:"varint,16,opt,name=cumulative_win,json=cumulativeWin,proto3" json:"cumulative_win,omitempty"`
	PlaySequence         int32                     `protobuf:"varint,17,opt,name=play_sequence,json=playSequence,proto3" json:"play_sequence,omitempty"`
	Transactions         []*WalletTransactionPB    `protobuf:"bytes,18,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Closed               bool                      `protobuf:"varint,19,opt,name=closed,proto3" json:"closed,omitempty"`
	RoundId              string                    `protobuf:"bytes,20,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GamestatePB) Reset()         { *m = GamestatePB{} }
func (m *GamestatePB) String() string { return proto.CompactTextString(m) }
func (*GamestatePB) ProtoMessage()    {}
func (*GamestatePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{3}
}

func (m *GamestatePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamestatePB.Unmarshal(m, b)
}
func (m *GamestatePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamestatePB.Marshal(b, m, deterministic)
}
func (m *GamestatePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamestatePB.Merge(m, src)
}
func (m *GamestatePB) XXX_Size() int {
	return xxx_messageInfo_GamestatePB.Size(m)
}
func (m *GamestatePB) XXX_DiscardUnknown() {
	xxx_messageInfo_GamestatePB.DiscardUnknown(m)
}

var xxx_messageInfo_GamestatePB proto.InternalMessageInfo

func (m *GamestatePB) GetGameId() GamestatePB_GameID {
	if m != nil {
		return m.GameId
	}
	return GamestatePB_DEFAULT
}

func (m *GamestatePB) GetEngineDef() int32 {
	if m != nil {
		return m.EngineDef
	}
	return 0
}

func (m *GamestatePB) GetBetPerLine() int64 {
	if m != nil {
		return m.BetPerLine
	}
	return 0
}

func (m *GamestatePB) GetCurrency() Ccy {
	if m != nil {
		return m.Currency
	}
	return Ccy_DEFAULT
}

func (m *GamestatePB) GetPreviousGamestate() []byte {
	if m != nil {
		return m.PreviousGamestate
	}
	return nil
}

func (m *GamestatePB) GetNextGamestate() []byte {
	if m != nil {
		return m.NextGamestate
	}
	return nil
}

func (m *GamestatePB) GetAction() GamestatePB_Action {
	if m != nil {
		return m.Action
	}
	return GamestatePB_base
}

func (m *GamestatePB) GetSymbolGrid() []*GamestatePB_Reel {
	if m != nil {
		return m.SymbolGrid
	}
	return nil
}

func (m *GamestatePB) GetPrizes() []*PrizePB {
	if m != nil {
		return m.Prizes
	}
	return nil
}

func (m *GamestatePB) GetSelectedWinLines() []int32 {
	if m != nil {
		return m.SelectedWinLines
	}
	return nil
}

func (m *GamestatePB) GetRelativePayout() int32 {
	if m != nil {
		return m.RelativePayout
	}
	return 0
}

func (m *GamestatePB) GetMultiplier() int32 {
	if m != nil {
		return m.Multiplier
	}
	return 0
}

func (m *GamestatePB) GetStopList() []int32 {
	if m != nil {
		return m.StopList
	}
	return nil
}

func (m *GamestatePB) GetNextActions() []GamestatePB_Action {
	if m != nil {
		return m.NextActions
	}
	return nil
}

func (m *GamestatePB) GetGamification() *GamestatePB_Gamification {
	if m != nil {
		return m.Gamification
	}
	return nil
}

func (m *GamestatePB) GetCumulativeWin() int64 {
	if m != nil {
		return m.CumulativeWin
	}
	return 0
}

func (m *GamestatePB) GetPlaySequence() int32 {
	if m != nil {
		return m.PlaySequence
	}
	return 0
}

func (m *GamestatePB) GetTransactions() []*WalletTransactionPB {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *GamestatePB) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *GamestatePB) GetRoundId() string {
	if m != nil {
		return m.RoundId
	}
	return ""
}

type GamestatePB_Reel struct {
	Symbols              []int32  `protobuf:"varint,1,rep,packed,name=symbols,proto3" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamestatePB_Reel) Reset()         { *m = GamestatePB_Reel{} }
func (m *GamestatePB_Reel) String() string { return proto.CompactTextString(m) }
func (*GamestatePB_Reel) ProtoMessage()    {}
func (*GamestatePB_Reel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{3, 0}
}

func (m *GamestatePB_Reel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamestatePB_Reel.Unmarshal(m, b)
}
func (m *GamestatePB_Reel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamestatePB_Reel.Marshal(b, m, deterministic)
}
func (m *GamestatePB_Reel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamestatePB_Reel.Merge(m, src)
}
func (m *GamestatePB_Reel) XXX_Size() int {
	return xxx_messageInfo_GamestatePB_Reel.Size(m)
}
func (m *GamestatePB_Reel) XXX_DiscardUnknown() {
	xxx_messageInfo_GamestatePB_Reel.DiscardUnknown(m)
}

var xxx_messageInfo_GamestatePB_Reel proto.InternalMessageInfo

func (m *GamestatePB_Reel) GetSymbols() []int32 {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type GamestatePB_Gamification struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Stage                int32    `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"`
	RemainingSpins       int32    `protobuf:"varint,3,opt,name=remaining_spins,json=remainingSpins,proto3" json:"remaining_spins,omitempty"`
	SpinsToStageUp       int32    `protobuf:"varint,4,opt,name=spins_to_stage_up,json=spinsToStageUp,proto3" json:"spins_to_stage_up,omitempty"`
	TotalSpins           int32    `protobuf:"varint,5,opt,name=total_spins,json=totalSpins,proto3" json:"total_spins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamestatePB_Gamification) Reset()         { *m = GamestatePB_Gamification{} }
func (m *GamestatePB_Gamification) String() string { return proto.CompactTextString(m) }
func (*GamestatePB_Gamification) ProtoMessage()    {}
func (*GamestatePB_Gamification) Descriptor() ([]byte, []int) {
	return fileDescriptor_4563ec715222b270, []int{3, 1}
}

func (m *GamestatePB_Gamification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamestatePB_Gamification.Unmarshal(m, b)
}
func (m *GamestatePB_Gamification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamestatePB_Gamification.Marshal(b, m, deterministic)
}
func (m *GamestatePB_Gamification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamestatePB_Gamification.Merge(m, src)
}
func (m *GamestatePB_Gamification) XXX_Size() int {
	return xxx_messageInfo_GamestatePB_Gamification.Size(m)
}
func (m *GamestatePB_Gamification) XXX_DiscardUnknown() {
	xxx_messageInfo_GamestatePB_Gamification.DiscardUnknown(m)
}

var xxx_messageInfo_GamestatePB_Gamification proto.InternalMessageInfo

func (m *GamestatePB_Gamification) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GamestatePB_Gamification) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *GamestatePB_Gamification) GetRemainingSpins() int32 {
	if m != nil {
		return m.RemainingSpins
	}
	return 0
}

func (m *GamestatePB_Gamification) GetSpinsToStageUp() int32 {
	if m != nil {
		return m.SpinsToStageUp
	}
	return 0
}

func (m *GamestatePB_Gamification) GetTotalSpins() int32 {
	if m != nil {
		return m.TotalSpins
	}
	return 0
}

func init() {
	proto.RegisterEnum("engine.Ccy", Ccy_name, Ccy_value)
	proto.RegisterEnum("engine.WalletTransactionPB_Type", WalletTransactionPB_Type_name, WalletTransactionPB_Type_value)
	proto.RegisterEnum("engine.GamestatePB_GameID", GamestatePB_GameID_name, GamestatePB_GameID_value)
	proto.RegisterEnum("engine.GamestatePB_Action", GamestatePB_Action_name, GamestatePB_Action_value)
	proto.RegisterType((*PayoutPB)(nil), "engine.PayoutPB")
	proto.RegisterType((*PrizePB)(nil), "engine.PrizePB")
	proto.RegisterType((*WalletTransactionPB)(nil), "engine.WalletTransactionPB")
	proto.RegisterType((*GamestatePB)(nil), "engine.GamestatePB")
	proto.RegisterType((*GamestatePB_Reel)(nil), "engine.GamestatePB.Reel")
	proto.RegisterType((*GamestatePB_Gamification)(nil), "engine.GamestatePB.Gamification")
}

func init() { proto.RegisterFile("datatypes_v1.proto", fileDescriptor_4563ec715222b270) }

var fileDescriptor_4563ec715222b270 = []byte{
	// 1854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x97, 0x6f, 0x77, 0x1a, 0xc7,
	0x15, 0xc6, 0x83, 0x90, 0x10, 0x1a, 0x10, 0xba, 0x1a, 0xff, 0xc3, 0x76, 0xe2, 0x10, 0x39, 0x8e,
	0xe5, 0x34, 0x71, 0x63, 0xd9, 0x6e, 0xe3, 0xb6, 0x69, 0x3a, 0xb0, 0xc3, 0xb2, 0x66, 0xd9, 0x5d,
	0xcd, 0xec, 0x1a, 0xa3, 0xb6, 0x67, 0x0e, 0x86, 0xb5, 0xba, 0xa7, 0x08, 0x28, 0xbb, 0xb2, 0xab,
	0xbe, 0xef, 0x39, 0xfd, 0x08, 0xfd, 0x16, 0xed, 0x27, 0xe9, 0xcb, 0x7e, 0x9e, 0x9e, 0x7b, 0x17,
	0x6c, 0xec, 0x38, 0x6d, 0xdf, 0xfd, 0xe6, 0x99, 0xbb, 0x33, 0x73, 0xef, 0x7d, 0x66, 0x38, 0x30,
	0x3e, 0x1e, 0x66, 0xc3, 0xec, 0x62, 0x1e, 0xa7, 0xe6, 0xd5, 0x83, 0xfb, 0xf3, 0xc5, 0x2c, 0x9b,
	0xf1, 0x52, 0x3c, 0x3d, 0x4d, 0xa6, 0xf1, 0xc1, 0x73, 0x56, 0x0e, 0x86, 0x17, 0xb3, 0xf3, 0x2c,
	0x68, 0xf2, 0xab, 0xac, 0x94, 0x5e, 0x9c, 0xbd, 0x98, 0x4d, 0xea, 0x85, 0x46, 0xe1, 0x70, 0x4b,
	0x2d, 0x47, 0xfc, 0x32, 0xdb, 0x1a, 0xcd, 0xce, 0xa7, 0x59, 0x7d, 0x83, 0xe4, 0x7c, 0xc0, 0x6f,
	0x31, 0x76, 0x76, 0x3e, 0xc9, 0x92, 0xf9, 0x24, 0x89, 0x17, 0xf5, 0x22, 0x4d, 0xad, 0x29, 0x07,
	0x7f, 0x2f, 0xb0, 0xed, 0x60, 0x91, 0xfc, 0x25, 0x0e, 0x9a, 0xfc, 0x90, 0x95, 0xe6, 0xb4, 0x0b,
	0xad, 0x5c, 0x39, 0x82, 0xfb, 0xf9, 0xf6, 0xf7, 0x57, 0x7b, 0xab, 0xe5, 0xfc, 0x7b, 0xab, 0x6e,
	0xbc, 0xbf, 0x2a, 0xbf, 0xc7, 0x20, 0x3f, 0x95, 0x99, 0xcf, 0xd2, 0x24, 0x4b, 0x66, 0xd3, 0xb4,
	0x5e, 0x6c, 0x14, 0x0f, 0xb7, 0xd4, 0x5e, 0xae, 0x07, 0x2b, 0x99, 0xd7, 0xd9, 0xf6, 0xeb, 0x64,
	0x3a, 0x49, 0xa6, 0x71, 0x7d, 0x93, 0xd6, 0x59, 0x0d, 0x0f, 0xfe, 0x5d, 0x60, 0x97, 0xfa, 0xc3,
	0xc9, 0x24, 0xce, 0xc2, 0xc5, 0x70, 0x9a, 0x0e, 0x47, 0xf8, 0x41, 0xd0, 0xe4, 0x35, 0xb6, 0x91,
	0x8c, 0xe9, 0x88, 0x3b, 0x6a, 0x23, 0x19, 0x63, 0x41, 0x86, 0x67, 0x6f, 0x32, 0x2f, 0xaa, 0xe5,
	0x88, 0x3f, 0x62, 0x9b, 0x58, 0x4e, 0x4a, 0xba, 0x76, 0xd4, 0x58, 0x25, 0xf3, 0x81, 0x25, 0xef,
	0x87, 0x17, 0xf3, 0x58, 0x51, 0x34, 0xbf, 0xcb, 0xca, 0xa3, 0xf3, 0xc5, 0x22, 0x9e, 0x8e, 0x2e,
	0xe8, 0x40, 0xb5, 0xa3, 0xca, 0xea, 0xcb, 0xd6, 0xe8, 0x42, 0xbd, 0x99, 0x3c, 0xf8, 0x96, 0x6d,
	0xe2, 0x67, 0xbc, 0xc2, 0xb6, 0x2d, 0xd9, 0x16, 0x91, 0x1b, 0xc2, 0x47, 0x7c, 0x87, 0x6d, 0xf5,
	0x85, 0x2d, 0x15, 0x14, 0x38, 0x63, 0xa5, 0x40, 0x0c, 0xfc, 0x28, 0x84, 0x0d, 0x5e, 0x65, 0x65,
	0xe9, 0x59, 0xca, 0x8f, 0x3c, 0x0b, 0x8a, 0x07, 0x7f, 0x05, 0x56, 0xb1, 0x87, 0x67, 0x71, 0x9a,
	0x0d, 0x33, 0xac, 0xfb, 0x43, 0xb6, 0x7d, 0x3a, 0x3c, 0x8b, 0xcd, 0x32, 0xab, 0xda, 0xd1, 0x8d,
	0xd5, 0x8e, 0x6b, 0x51, 0xc4, 0x8e, 0xa5, 0x4a, 0x18, 0xea, 0x8c, 0xf9, 0x27, 0x8c, 0xe5, 0x41,
	0x66, 0x1c, 0xbf, 0x5c, 0xb6, 0x60, 0x27, 0x57, 0xac, 0xf8, 0x25, 0x6f, 0xb0, 0xea, 0x8b, 0x38,
	0x33, 0xf3, 0x78, 0x61, 0xa8, 0xb6, 0x45, 0x2a, 0x0d, 0x7b, 0x11, 0x67, 0x41, 0xbc, 0x70, 0x93,
	0xe9, 0xff, 0x9f, 0x28, 0xff, 0x9a, 0xf1, 0xf9, 0x22, 0x7e, 0x95, 0xcc, 0xce, 0x53, 0x73, 0xba,
	0x3a, 0x50, 0x7d, 0xab, 0x51, 0x38, 0xac, 0xaa, 0xfd, 0xd5, 0xcc, 0x9b, 0x93, 0xf2, 0x3b, 0xac,
	0x36, 0x8d, 0xff, 0x9c, 0xad, 0x85, 0x96, 0x28, 0x74, 0x17, 0xd5, 0xb7, 0x61, 0x47, 0xac, 0x94,
	0x97, 0xbf, 0xbe, 0xfd, 0xe3, 0x39, 0x0b, 0x8a, 0x50, 0xcb, 0x48, 0xfe, 0x84, 0x55, 0x96, 0xb6,
	0x3a, 0x5d, 0x24, 0xe3, 0x7a, 0xb9, 0x51, 0x3c, 0xac, 0x1c, 0xd5, 0x3f, 0xf4, 0xa1, 0x8a, 0xe3,
	0x89, 0x62, 0x79, 0xb0, 0xbd, 0x48, 0xc6, 0xfc, 0x2e, 0x2b, 0xcd, 0xd1, 0xe6, 0x69, 0x7d, 0x87,
	0xbe, 0xda, 0x7b, 0xe3, 0xed, 0xdc, 0xfc, 0x6a, 0x39, 0xcd, 0xbf, 0x62, 0x3c, 0x8d, 0x27, 0xf1,
	0x28, 0x8b, 0xc7, 0xe6, 0x75, 0x32, 0xa5, 0xea, 0xa5, 0x75, 0x46, 0xe6, 0x85, 0xd5, 0x4c, 0x3f,
	0x99, 0x62, 0x0d, 0x53, 0x7e, 0x97, 0xed, 0x2d, 0xe2, 0xc9, 0x30, 0x4b, 0x5e, 0xc5, 0x66, 0x79,
	0x77, 0x2a, 0xd4, 0x8a, 0xda, 0x4a, 0x0e, 0x3e, 0x74, 0x63, 0xaa, 0x3f, 0xb8, 0x31, 0x37, 0xd9,
	0x4e, 0x9a, 0xcd, 0xe6, 0x66, 0x92, 0xa4, 0x59, 0x7d, 0x97, 0x76, 0x2b, 0xa3, 0xe0, 0x26, 0x69,
	0xc6, 0xbf, 0x63, 0x55, 0x2a, 0x69, 0x5e, 0x86, 0xb4, 0x5e, 0x6b, 0x14, 0xff, 0x47, 0xc5, 0x2a,
	0x18, 0x9f, 0x73, 0xca, 0x2d, 0x56, 0x3d, 0x1d, 0x9e, 0x25, 0x2f, 0x93, 0xd1, 0x90, 0x0a, 0xbe,
	0x47, 0xb7, 0xbb, 0xf1, 0x23, 0x26, 0x7b, 0x13, 0xa7, 0xde, 0xf9, 0x0a, 0xfb, 0x3a, 0x3a, 0x3f,
	0x3b, 0x5f, 0x26, 0xfb, 0x3a, 0x99, 0xd6, 0x81, 0x3c, 0xb5, 0xfb, 0x56, 0xed, 0x27, 0x53, 0x7e,
	0x9b, 0xed, 0xce, 0x27, 0xc3, 0x0b, 0x93, 0xc6, 0x7f, 0x3a, 0x8f, 0xa7, 0xa3, 0xb8, 0xbe, 0x4f,
	0xb9, 0x56, 0x51, 0xd4, 0x4b, 0x8d, 0x7f, 0xcf, 0xaa, 0xd9, 0xdb, 0x0b, 0x98, 0xd6, 0x39, 0xf5,
	0xe4, 0xe6, 0x7f, 0xb9, 0xa2, 0xea, 0x9d, 0x0f, 0xf0, 0xce, 0x8f, 0x26, 0xb3, 0x34, 0x1e, 0xd7,
	0x2f, 0x35, 0x0a, 0x87, 0x65, 0xb5, 0x1c, 0xf1, 0xeb, 0xac, 0xbc, 0x98, 0x9d, 0x4f, 0xc7, 0x78,
	0x97, 0x2e, 0xd3, 0x0b, 0xb1, 0x4d, 0x63, 0x67, 0x7c, 0xa3, 0xc1, 0x36, 0xd1, 0x15, 0xf8, 0xe0,
	0xe4, 0xbe, 0x48, 0xeb, 0x05, 0xaa, 0xf3, 0x6a, 0x78, 0xe3, 0x1f, 0x05, 0x56, 0x5d, 0x2f, 0x00,
	0x3e, 0xa9, 0x93, 0xf8, 0x55, 0xbc, 0x7a, 0x69, 0xf3, 0x01, 0xaa, 0x69, 0x36, 0x3c, 0x8d, 0x57,
	0x0f, 0x2d, 0x0d, 0x72, 0x27, 0x9c, 0x0d, 0x93, 0x69, 0x32, 0x3d, 0x35, 0xe9, 0x3c, 0xa1, 0x17,
	0x6f, 0xe9, 0x84, 0xa5, 0xac, 0x51, 0xe5, 0xf7, 0xd8, 0x3e, 0x4d, 0x9b, 0x6c, 0x66, 0xe8, 0x53,
	0x73, 0x3e, 0x5f, 0x3e, 0x7d, 0x35, 0x9a, 0x08, 0x67, 0x1a, 0xe5, 0x68, 0xce, 0x3f, 0x65, 0x95,
	0x6c, 0x96, 0x0d, 0x27, 0xcb, 0xf5, 0xb6, 0x72, 0xd7, 0x90, 0x44, 0x6b, 0x1d, 0xfc, 0xad, 0xc4,
	0x4a, 0xf9, 0xbb, 0xf0, 0xee, 0x33, 0x74, 0x89, 0xed, 0x85, 0x1d, 0x69, 0x06, 0x52, 0x28, 0xe3,
	0xb7, 0xcd, 0x49, 0x27, 0xca, 0x1f, 0xa4, 0x13, 0xdf, 0x72, 0x44, 0x0b, 0x36, 0xf8, 0x2e, 0xdb,
	0x69, 0x89, 0xd0, 0x84, 0x1d, 0x47, 0xb6, 0xa1, 0xc8, 0xaf, 0xb0, 0xfd, 0xb0, 0xa3, 0xa4, 0x34,
	0x5d, 0xc7, 0xb3, 0x2d, 0xbf, 0x67, 0x74, 0x27, 0x82, 0xcd, 0x1f, 0xca, 0x7d, 0xe9, 0xc0, 0x16,
	0xbf, 0xcc, 0xe0, 0x3d, 0x39, 0x82, 0x12, 0xbf, 0xca, 0x78, 0x4b, 0x39, 0x3d, 0xed, 0x7b, 0xa6,
	0x27, 0xf4, 0x71, 0x24, 0x95, 0xb0, 0x24, 0x6c, 0xf3, 0x3d, 0x56, 0x79, 0x1a, 0x79, 0xb6, 0x2b,
	0x8d, 0x16, 0xb6, 0x80, 0x32, 0x0a, 0x2d, 0xe1, 0x59, 0x03, 0x63, 0x3b, 0xca, 0xd5, 0xb0, 0x83,
	0xeb, 0xf5, 0xa3, 0xae, 0xef, 0xd9, 0x26, 0x54, 0x52, 0xe8, 0x48, 0x49, 0x0d, 0x8c, 0x03, 0xab,
	0xea, 0x50, 0x49, 0x19, 0x1a, 0x25, 0x5a, 0x52, 0x41, 0x05, 0x95, 0xa6, 0x68, 0x8a, 0xae, 0x36,
	0xc7, 0x91, 0xd4, 0x21, 0x54, 0x79, 0x8d, 0x31, 0xa1, 0x43, 0xe5, 0x1b, 0x5b, 0xf6, 0x34, 0xec,
	0xe2, 0xf3, 0x1b, 0x08, 0xcf, 0x12, 0x50, 0xc3, 0x45, 0xf1, 0x78, 0x98, 0xbe, 0x2d, 0x7a, 0x4d,
	0x57, 0x2a, 0x0d, 0x7b, 0x58, 0x18, 0xa1, 0x42, 0x14, 0xb1, 0x3e, 0x6d, 0x47, 0x87, 0x00, 0x9c,
	0xb3, 0x9a, 0x96, 0x42, 0xfb, 0x9e, 0x36, 0x7d, 0xc7, 0x0b, 0xa5, 0x82, 0xfd, 0x75, 0x4d, 0x07,
	0xca, 0xf1, 0x6c, 0xe0, 0xef, 0x68, 0x51, 0xaf, 0x27, 0x15, 0x5c, 0x5a, 0xd7, 0x44, 0x14, 0x46,
	0x3d, 0x0f, 0x2e, 0x63, 0x2b, 0x96, 0x1a, 0x5c, 0xc1, 0x43, 0xb7, 0x55, 0xe4, 0x84, 0x03, 0xf3,
	0x4c, 0x2a, 0x2d, 0xe1, 0x2a, 0x2a, 0xc2, 0xb4, 0x85, 0xa3, 0x06, 0x26, 0x14, 0xae, 0x84, 0x6b,
	0x74, 0x2a, 0xd3, 0x71, 0x2c, 0x4b, 0x7a, 0xa6, 0xed, 0x2b, 0xcc, 0xad, 0x8e, 0xb9, 0x35, 0x45,
	0x18, 0xba, 0xb2, 0x27, 0x5b, 0x1d, 0xb8, 0x8e, 0x09, 0x09, 0xd3, 0x73, 0x5c, 0xd7, 0xf1, 0x3d,
	0xe3, 0x3a, 0x76, 0x27, 0xd4, 0x70, 0x03, 0x9b, 0xda, 0x74, 0xb0, 0x04, 0x70, 0x13, 0xb9, 0xe5,
	0xfa, 0x91, 0xf5, 0x04, 0x3e, 0xc6, 0x68, 0x57, 0x60, 0x2e, 0x9e, 0x69, 0x4b, 0x1d, 0x3a, 0xcf,
	0x84, 0x0b, 0x9f, 0xf0, 0x9b, 0xec, 0x9a, 0x30, 0x6b, 0xc5, 0x37, 0xad, 0x8e, 0x72, 0x74, 0xd8,
	0x13, 0x1a, 0x6e, 0xe1, 0x86, 0xba, 0x3b, 0x30, 0x4f, 0x65, 0x5f, 0xba, 0x1a, 0x3e, 0xc5, 0x73,
	0x06, 0x52, 0x28, 0x17, 0xcb, 0xd4, 0x91, 0x0a, 0x1a, 0xbc, 0xcc, 0x36, 0x6d, 0x5f, 0xb8, 0xf0,
	0x19, 0xb9, 0x4d, 0x0c, 0x42, 0xdf, 0x13, 0x70, 0x90, 0x9f, 0x6c, 0xe5, 0x35, 0x57, 0xf8, 0x68,
	0x9e, 0xdb, 0xd8, 0x66, 0x4b, 0x09, 0x1b, 0xed, 0x30, 0xd0, 0x21, 0x7c, 0x8e, 0x61, 0x2d, 0xdf,
	0xef, 0xfa, 0xed, 0xb6, 0x69, 0x75, 0x44, 0x2f, 0x70, 0x7c, 0x0f, 0xee, 0xbc, 0x75, 0x83, 0xee,
	0x09, 0xdd, 0x81, 0x2f, 0xb0, 0x18, 0xcf, 0x84, 0xeb, 0xca, 0x01, 0xae, 0x86, 0x2d, 0xd4, 0x70,
	0x17, 0x9d, 0xd8, 0x52, 0xe2, 0x64, 0x60, 0xa4, 0xd0, 0xa1, 0x54, 0x46, 0xda, 0xb6, 0x86, 0x43,
	0xec, 0xb7, 0xa5, 0x9c, 0x76, 0x08, 0xf7, 0x0e, 0xfe, 0x59, 0x60, 0xa5, 0xfc, 0xc1, 0xc3, 0x63,
	0xbe, 0x18, 0xa6, 0x31, 0x7c, 0x84, 0x15, 0x79, 0x99, 0x4c, 0x93, 0xf4, 0x0f, 0x50, 0xc0, 0xdf,
	0xe0, 0x97, 0x8b, 0x38, 0xc6, 0xab, 0x94, 0x5f, 0x80, 0x79, 0x32, 0xfa, 0x23, 0x5d, 0x23, 0x28,
	0x62, 0xe0, 0x22, 0x9f, 0xda, 0xc4, 0xa9, 0x55, 0xe0, 0x11, 0x6c, 0xad, 0x0f, 0x1f, 0x42, 0x69,
	0x7d, 0xf8, 0x08, 0xb6, 0xd7, 0x87, 0x8f, 0xa1, 0x8c, 0x35, 0x5c, 0x0d, 0x1f, 0x7c, 0x03, 0x3b,
	0xeb, 0xe3, 0xa3, 0xc7, 0xc0, 0xb0, 0x6e, 0xa3, 0x61, 0x3a, 0x1a, 0x8e, 0x63, 0xa8, 0x7c, 0xf9,
	0xaf, 0x12, 0x2b, 0xb6, 0x46, 0x17, 0xef, 0x5e, 0xdd, 0x6d, 0x56, 0x6c, 0x79, 0x03, 0x28, 0x20,
	0x44, 0xda, 0x82, 0x0d, 0x04, 0xbb, 0x19, 0x40, 0x11, 0x41, 0x46, 0x0a, 0x36, 0x11, 0x9e, 0x06,
	0x03, 0x28, 0x21, 0x84, 0x9d, 0x26, 0x6c, 0x23, 0xf4, 0x06, 0x0a, 0xca, 0x08, 0xcf, 0x3c, 0x0b,
	0x76, 0x10, 0xba, 0xaa, 0x0f, 0x0c, 0xc1, 0xb1, 0xf0, 0xfa, 0x6c, 0xb3, 0xe2, 0x89, 0x50, 0x50,
	0x45, 0x78, 0xde, 0x0c, 0x61, 0x97, 0x3e, 0x57, 0x03, 0xa8, 0x21, 0x88, 0x9e, 0x05, 0x7b, 0x08,
	0x9e, 0xdf, 0x05, 0x40, 0xd0, 0xb2, 0x0b, 0xfb, 0x08, 0x2a, 0x6a, 0x02, 0xa7, 0x05, 0x4f, 0x42,
	0xb8, 0x44, 0x7b, 0xf5, 0xba, 0x70, 0x99, 0xe0, 0xb9, 0x07, 0x57, 0x10, 0x9a, 0x7e, 0x13, 0xae,
	0x22, 0x04, 0x03, 0x1b, 0xae, 0x11, 0x48, 0x0f, 0xea, 0x94, 0x8e, 0x1b, 0xc0, 0x75, 0x4a, 0x67,
	0x10, 0xc1, 0x0d, 0x52, 0x84, 0x05, 0x37, 0x69, 0x53, 0x69, 0xc1, 0xc7, 0x04, 0x2e, 0xda, 0x13,
	0xc1, 0x17, 0x70, 0x8b, 0x40, 0xa1, 0x07, 0x11, 0x22, 0x0b, 0x1a, 0x04, 0x27, 0x1e, 0x7c, 0x46,
	0x7b, 0x89, 0x1e, 0x1c, 0x10, 0x58, 0x21, 0xdc, 0x26, 0xb0, 0x3d, 0xf8, 0x9c, 0xa0, 0x63, 0xc1,
	0x1d, 0x02, 0xcf, 0x82, 0x2f, 0x08, 0xfa, 0x01, 0xdc, 0xa5, 0x4d, 0xad, 0x36, 0x1c, 0x12, 0x74,
	0xda, 0x70, 0x8f, 0x40, 0xb5, 0xe0, 0x4b, 0x02, 0x3f, 0x80, 0x9f, 0x10, 0x9c, 0x74, 0xe1, 0x2b,
	0x04, 0xab, 0xdb, 0x85, 0xaf, 0x09, 0xfc, 0x00, 0xee, 0x53, 0xe5, 0xed, 0x00, 0x7e, 0x4a, 0xbd,
	0x90, 0x2e, 0x7c, 0x43, 0xd0, 0xd1, 0xf0, 0x80, 0xc0, 0x09, 0xe0, 0x88, 0xc0, 0x6b, 0xc3, 0x43,
	0x82, 0xf0, 0x18, 0x1e, 0x21, 0x74, 0xba, 0x16, 0x3c, 0x26, 0x50, 0x5d, 0xf8, 0x19, 0x41, 0x68,
	0xc3, 0xcf, 0x09, 0xa2, 0x36, 0x7c, 0x4b, 0xdd, 0x71, 0x35, 0x3c, 0x21, 0xf0, 0x14, 0xfc, 0x82,
	0xe0, 0xd8, 0x85, 0x5f, 0x12, 0x28, 0x05, 0xbf, 0x22, 0xd0, 0x5d, 0xf8, 0x8e, 0xfa, 0xee, 0x5b,
	0xf0, 0x6b, 0xea, 0x85, 0xd4, 0xf0, 0x3d, 0x41, 0xdf, 0x82, 0xdf, 0x20, 0xb8, 0xcd, 0x00, 0x04,
	0x81, 0x76, 0xa1, 0x49, 0xdd, 0x11, 0x16, 0xb4, 0x08, 0x9a, 0x2d, 0xb0, 0x08, 0xba, 0x4d, 0x90,
	0x04, 0xfd, 0x2e, 0xb4, 0xa9, 0xdd, 0xc2, 0x02, 0x9b, 0xc0, 0xf6, 0xa0, 0x43, 0x70, 0x62, 0x81,
	0x83, 0xe0, 0xf7, 0x14, 0x3c, 0x25, 0xdb, 0xf4, 0xfa, 0xd0, 0xa5, 0x9e, 0x76, 0x02, 0x70, 0x09,
	0x5c, 0x0f, 0x7a, 0x64, 0x24, 0xbf, 0x0d, 0x1e, 0xc2, 0xb1, 0x50, 0xe0, 0x93, 0x5b, 0x7c, 0x0f,
	0x02, 0x02, 0x6d, 0xc1, 0x31, 0x41, 0xbf, 0x0d, 0x8a, 0x1c, 0x25, 0x14, 0x68, 0x02, 0xdb, 0x82,
	0x90, 0xec, 0xd7, 0x0b, 0x21, 0x22, 0xf0, 0x2c, 0x78, 0x46, 0xd0, 0xb7, 0xa0, 0x4f, 0x70, 0xa2,
	0xe1, 0x39, 0xd9, 0x46, 0x74, 0x60, 0x40, 0xd0, 0x6c, 0xc1, 0x09, 0x81, 0xfd, 0x1c, 0x7e, 0x4b,
	0xbb, 0x8b, 0x36, 0xfc, 0x8e, 0x3c, 0x2f, 0x35, 0xfc, 0xfe, 0x45, 0x89, 0xfe, 0x35, 0x3d, 0xfc,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xd6, 0x90, 0x14, 0x4b, 0x0d, 0x00, 0x00,
}
