---
kind: ConfigMap
apiVersion: v1
metadata:
  name: parameterconfig
  namespace: {{ .Values.namespace | default "maverick" }}
  labels:
  {{- include "rgs-v2.labels" . | nindent 4 }}
data:
  parameterConfig.yml: |
    # default range of stake values

    stakeValues:
      - 1
      - 2
      - 3
      - 5
      - 10
      - 20
      - 30
      - 50
      - 100
      - 200
      - 300
      - 500
      - 1000
      - 2000
      - 3000
      - 5000

    defaultBet: 5 # index of stakeValues

    ccyMultipliers:
      AED: 0.03
      ALL: 1
      AMD: 5
      AOA: 3
      ARS: 0.5
      ARX: 1.25
      AZN: 0.01
      BAM: 0.01
      BCH: 0.001
      BDT: 0.5
      BGN: 0.01
      BHD: 0.005
      BND: 0.01
      BOB: 0.05
      BRL: 0.04
      BTC: 0.001
      BWP: 0.05
      BYN: 0.02
      CAD: 0.01
      CDF: 10
      CHF: 0.01
      CLP: 5
      CNY: 0.04
      COP: 50
      CRC: 5
      CZK: 0.2
      DKK: 0.5
      DOP: 0.5
      EGP: 0.25
      ETH: 0.001
      EUR: 0.01
      GBP: 0.01
      GEL: 0.02
      GHS: 0.05
      GIP: 0.01
      GNF: 500
      GTQ: 0.05
      HKD: 0.05
      HRK: 0.05
      HTG: 0.5
      HUF: 5
      IDR: 100
      ILS: 0.03
      INR: 1
      IQD: 25
      IRR: 250
      ISK: 1
      JOD: 0.01
      JPY: 1
      KES: 1
      KGS: .8
      KRW: 10
      KWD: 0.005
      KZT: 3.5
      LBP: 25
      LKR: 1.5
      LSL: 0.1
      LTC: 0.001
      MAD: 0.1
      MBC: 0.01
      MDL: 0.15
      MGA: 30
      MKD: 0.5
      MMK: 10
      MWK: 1
      MXN: 0.2
      MYR: 0.02
      NAD: 0.05
      NGN: 1
      NOK: 0.01
      NZD: 0.1
      OMR: 0.005
      PEN: 0.02
      PLN: 0.3
      PYG: 50
      QAR: 0.03
      RON: 0.04
      RSD: 1
      RUB: 0.5
      RWF: 5
      SAR: 0.03
      SEK: 0.01
      THB: 0.2
      TJS: .1
      TMT: 0.03
      TND: 0.02
      TRY: 0.05
      TZS: 50
      UAH: 0.25
      UBC: 1
      UGX: 50
      USD: 0.01
      UST: 0.01
      UYU: 0.4
      UZS: 50
      VES: 0.004
      VEX: 2000
      VND: 100
      XAF: 5
      XBT: 0.001
      XOF: 5
      ZAR: 0.1
      ZMK: 0.1
      ZMW: 0.1

    profiles:
      low:
        max: 11
        default: 2
      high:
        min: 5
        default: 10
      base:
        default: 2
        max: 10
      highdefault:
        default: 4
        max: 13

    hostProfiles:
      maverick: low
      THB: highdefault

    override:
      mvgEngineV:
        UZS:
          defaultBet: 120
          stakeValues:
            - 40  
            - 80  
            - 120 
            - 200 
            - 400 
            - 800 
            - 1200  
            - 2000  
            - 4000  
            - 8000
      mvgEngineIX:
        UZS:
          defaultBet: 3000
          stakeValues:
            - 1000
            - 2000
            - 3000
            - 5000
            - 10000
            - 20000
            - 30000
            - 50000
            - 100000
            - 200000
      mvgEngineX:
        UZS:
          defaultBet: 1500
          stakeValues:
            - 1
            - 1
            - 1
            - 1
            - 1
            - 1
            - 1500
            - 1
            - 1
            - 1
      mvgEngineXI:
        UZS:
          defaultBet: 3000
          stakeValues:
            - 1000
            - 2000
            - 3000
            - 5000
            - 10000
            - 20000
            - 30000
            - 50000
            - 100000
            - 200000
      mvgEngineXII:
        UZS:
          defaultBet: 75
          stakeValues:
            - 25  
            - 50  
            - 75  
            - 125 
            - 250 
            - 500 
            - 750 
            - 1250  
            - 2500  
            - 5000
      mvgEngineXIII:
        UZS:
          defaultBet: 60
          stakeValues:
            - 20  
            - 40  
            - 60  
            - 100 
            - 200 
            - 400 
            - 600 
            - 1000  
            - 2000  
            - 4000
      mvgEngineXIV:
        UZS:
          defaultBet: 60
          stakeValues:
            - 20  
            - 40  
            - 60  
            - 100 
            - 200 
            - 400 
            - 600 
            - 1000  
            - 2000  
            - 4000
      mvgEngineXV:
        UZS:
          defaultBet: 120
          stakeValues:
            - 40  
            - 80  
            - 120 
            - 200 
            - 400 
            - 800 
            - 1200  
            - 2000  
            - 4000  
            - 8000
      mvgEngineXVI:
        UZS:
          defaultBet: 75
          stakeValues:
            - 25  
            - 50  
            - 75  
            - 125 
            - 250 
            - 500 
            - 750 
            - 1250  
            - 2500  
            - 5000
      mvgEngineUnity1:
        credits:
          defaultBet: 10
          stakeValues:
            - 3
            - 5
            - 10
            - 20
            - 30
            - 50
            - 100
            - 200
            - 300
            - 500
