---
kind: ConfigMap
apiVersion: v1
metadata:
  name: parameterconfig
  namespace: {{ .Values.namespace | default "maverick" }}
  labels:
  {{- include "rgs-v2.labels" . | nindent 4 }}
data:
  parameterConfig.yml: |-
    {{- .Files.Get "parameterConfig.yml" | nindent 4 }}