apiVersion: v1
kind: Service
metadata:
  name: {{ include "rgs-v2.fullname" . }}
  namespace: maverick
  labels:
    {{- include "rgs-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rgs
      protocol: TCP
      name: rgs
  selector:
    {{- include "rgs-v2.selectorLabels" . | nindent 4 }}
