# Default values for rgs-v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: elysium

image:
  repo: "harbor.elysiumstudios.se/elysium/"
  name: "mvg_rgs"

imagePullSecrets:
  - name: harborcred

nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/http2-push-preload: "true"
    field.cattle.io/ingressState: "{}"
    nginx.ingress.kubernetes.io/configuration-snippet: "more_set_headers \"Access-Control-Expose-Headers: ETag\";"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, If-Match"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-max-age: "151200"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: public.elysiumstudios.se
      paths:
        - path: /v2
          pathType: Prefix
  tls: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

volumes:
  - engineconfigs
  - baseconfigs
  - parameterconfig
  - forcetool

affinity: {}

livenessProbe:
  path: /v2/rgs/healthcheck
  port: rgs
  initialDelaySeconds: 5
  periodSeconds: 30

readinessProbe:
  path: /v2/rgs/healthcheck
  port: rgs
  initialDelaySeconds: 5
  periodSeconds: 30

config:
  devmode: false
  local: false
  logging: debug
  environment: production
  mcrouter: ""
  server:
    host: "0.0.0.0"
    port: 3000
    name: elysium
#  storeurl: "http://gnrc-integ.dashur-integ/v1/gnrc/maverick"
  storeurl: "https://gnrc-api.maverick-ops.com/v1/gnrc/maverick"
  storeappid: "HAAJ6njttH"
  storeapppass: "WKXUZWTzNzvmTqYxiHnH9hKc"
  defaultlanguage: "en"
  defaultplatform: "html5"
  demotokenprefix: "demo-token-e6ENjpt76fe8gun9vccRpEP"
  democurrency: "USD"
  logaccount: "145472021_144443389"
  datalimit: 3200
  localdatattl: 3600
  extplaycheck: "https://dev.elysiumstudios.se/game-history"

gameConfig:
  - engineID: mvgEngineI
    games:
      - name: the-year-of-zhu
        item: 5124
      - name: cat-thief
        item: 5113
      - name: lantern-festival
        item: 5131
      - name: crimson-masquerade
        item: 5114
      - name: babaks-quest
        item: 5110
      - name: astro-gems
        item: 5109
      - name: jungle-saga
        item: 5116
      - name: wukong-treasures
        item: 5128
      - name: three-kingdom-shu
        item: 5125
  - engineID: mvgEngineII
    games:
      - name: zodiac
        item: 5129
      - name: street-racer
        item: 5123
      - name: panda
        item: 5118
      - name: three-kingdom-wu
        item: 5127
      - name: candy-girls
        item: 5112
      - name: bistro
        item: 5130
  - engineID: mvgEngineIII
    games:
      - name: three-kingdom-wei
        item: 5126      
      - name: king-of-gamblers
        item: 5117
      - name: a-million-lights
        item: 5134
  - engineID: mvgEngineV
    games:
      - name: a-fairy-tale
        item: 5104
      - name: a-candy-girls-christmas
        item: 5139
  - engineID: mvgEngineVII
    games:
      - name: art-of-the-fist
        item: 5108
      - name: battlemech
        item: 5111
      - name: a-year-of-laoshu
        item: 5170
      - name: candy-smash
        item: 5376
  - engineID: mvgEngineIX
    games:
      - name: fruity-verse
        item: 5115
      - name: a-hidden-forest
        item: 5106
      - name: daytona
        item: 5171
      - name: crazy-easter-eggs
        item: 5445
  - engineID: mvgEngineX
    games:
      - name: seasons-winter
        item: 5122
      - name: seasons-spring
        item: 5120
      - name: seasons-summer
        item: 5121
      - name: seasons-autumn
        item: 5119
      - name: seasons
  - engineID: mvgEngineXII
    games:
      - name: cloud9
        item: 5132
      - name: pearl-fisher
        item: 5136
      - name: dragon-myst
        item: 5377
  - engineID: mvgEngineXIII
    games:
      - name: sky-jewels
        item: 5135
      - name: goal
        item: 5169
      - name: cookoff-champion
        item: 5378
      - name: drift
        item: 5471
  - engineID: mvgEngineXIV
    games:
      - name: valley-of-kings
        item: 5494
      - name: bangkok-fighter
        item: 5610
      - name: asuka-x-samurai
        item: 5613
      - name: battlemech-mars
        item: 5721
  - engineID: mvgEngineXI
    games:
      - name: mah-jong
        item: 5612
  - engineID: mvgEngineXV
    games:
      - name: museum
        item: 5611
  - engineID: mvgEngineXVI
    games:
      - name: sparta
        item: 6199
  - engineID: mvgEngineUnity1
    games:
      - name: supa-crew
        item: 7523
  - engineID: mvgEngineGodot2
    games:
      - name: fox-tale
        item: 7797
  - engineID: mvgEngineRoulette1
    category: roulette
    games:
      - name: dragon-roulette
        item: 7863
  - engineID: mvgEngineGodot3
    games:
      - name: spirit-hunters
        item: 7985
  - engineID: mvgEngineGodot4
    games:
      - name: wizardz-world
        item: 8243
  - engineID: mvgEngineGodot5
    games:
      - name: battle-of-myths
        item: 8359
  - engineID: mvgEngineGodot6
    games:
      - name: sword-king
      
gamification:
  a-fairy-tale:
    function: Increment
    stages: 3
  a-candy-girls-christmas:
    function: Increment
    stages: 3
  battlemech:
    function: Increment
    stages: 3
  candy-smash:
    function: Increment
    stages: 3
  sky-jewels:
    function: IncrementSpins
    stages: 6
    spinsMin: 20
    spinsMax: 50
  drift:
    function: IncrementSpins
    stages: 5
    spinsMin: 30
    spinsMax: 50
  goal:
    function: IncrementSpins
    stages: 3
    spinsMin: 50
    spinsMax: 70
  cookoff-champion:
    function: IncrementSpins
    stages: 3
    spinsMin: 50
    spinsMax: 70
  bangkok-fighter:
    function: IncrementSpins
    stages: 1
    spinsMin: 50
    spinsMax: 70
  asuka-x-samurai:
    function: IncrementSpins
    stages: 5
    spinsMin: 50
    spinsMax: 70
  battlemech-mars:
    function: IncrementSpins
    stages: 5
    spinsMin: 50
    spinsMax: 70
