# this is overwritten in deployment by configmap, use only for local development
# development mode
devmode: true
local: true

# Log levels
# debug, info, warn, error, fatal
logging: debug

# mcrouter address
mcrouter: "127.0.0.1:11211"

# server configuration
server:
  host: "0.0.0.0"
  port: 3000

dashurconf:
  storeurl: https://gnrc-api.dashur.io/v1/gnrc/maverick
  storeappid: VrCLq4UqYBf39rJt
  storeapppass: V6Kg9muzJxsz3nWFvJeyccU7

defaultlanguage: en
defaultplatform: html5
#dashurconf:
# this is for prod version of dashur
#  storeurl: https://gnrc-api.maverick-ops.com/v1/gnrc/maverick
#  storeappid: HAAJ6njttH
#  storeapppass: WKXUZWTzNzvmTqYxiHnH9hKc
#demotokenprefix: demo-token-e6ENjpt76fe8gun9vccRpEPN
demotokenprefix: demo-token-ezVVKaEv2nY7kP2gMCX7vfCH
democurrency: USD