
- engineID: mvgEngineI
  games:
    - the-year-of-zhu
    - cat-thief
    - lantern-festival
    - crimson-masquerade
    - babaks-quest
    - astro-gems
    - jungle-saga
    - wukong-treasures
    - three-kingdom-shu
- engineID: mvgEngineII
  games:
    - zodiac
    - street-racer
    - panda
    - three-kingdom-wu
    - candy-girls
    - bistro
- engineID: mvgEngineIII
  games:
    - three-kingdom-wei
    - king-of-gamblers
    - a-million-lights
- engineID: mvgEngineV
  games:
    - a-fairy-tale
    - a-candy-girls-christmas
- engineID: mvgEngineVII
  games:
    - art-of-the-fist
    - battlemech
    - a-year-of-laoshu
    - candy-smash
- engineID: mvgEngineIX
  games:
    - fruity-verse
    - a-hidden-forest
    - daytona
    - crazy-easter-eggs
- engineID: mvgEngineX
  games:
    - seasons-winter
    - seasons-spring
    - seasons-summer
    - seasons-autumn
    - seasons
- engineID: mvgEngineXII
  games:
    - cloud9
    - pearl-fisher
    - dragon-myst
- engineID: mvgEngineXIII
  games:
    - sky-jewels
    - goal
    - cookoff-champion
    - drift
    - princess
- engineID: mvgEngineXIV
  games:
    - valley-of-kings
    - bangkok-fighter
    - asuka-x-samurai
    - battlemech-mars
- engineID: mvgEngineXI
  games:
    - mah-jong
- engineID: mvgEngineXV
  games:
    - museum
- engineID: mvgEngineXVI
  games:
    - sparta
- engineID: mvgEngineXVII
  games:
    - book-of-living
- engineID: mvgEngineXVIII
  games:
    - zodiac-elements
- engineID: testRespin
  games:
    - test-respin
- engineID: mvgEngineUnity1
  games:
    - supa-crew