# default range of stake values

stakeValues:
  - 1
  - 2
  - 3
  - 5
  - 10
  - 20
  - 30
  - 50
  - 100
  - 200
  - 300
  - 500
  - 1000
  - 2000
  - 3000
  - 5000

defaultBet: 5 # index of stakeValues

ccyMultipliers:
  USD: 0.01
  CNY: 0.04
  EUR: 0.01
  GBP: 0.01
  VND: 100
  KRW: 10
  ZAR: 0.1
  JPY: 1
  THB: 0.2
  MYR: 0.02
  IDR: 100
  XBT: 0.004
  TRY: 0.05
  BRL: 0.04
  SEK: 0.01
  RUB: 0.5
  KZT: 3.5
  NOK: 0.01
  AMD: 5
  MMK: 10
  MXN: 0.2
  BOB: 0.05
  PYG: 50
  PEN: 0.02
  CLP: 5
  UYU: 0.4
  CAD: 0.01
  AED: 0.03
  ALL: 1
  AOA: 3
  ARS: 0.5
  AZN:
  BAM:
  BDT:
  BGN:
  BHD:
  BND:
  BWP:
  CDF:
  CHF:
  CRC:
  COP:
  CZK:
  DKK:
  DOP:
  EGP:
  GEL:
  GHS:
  GIP:
  GNF:
  GTQ:
  HKD:
  HRK:
  HTG:
  HUF:
  ILS:
  INR:
  IQD:
  IRR:
  ISK:
  JOD:
  KES:
  KWD:
  LBP:
  LSL:
  MAD:
  MBC:
  MKD:
  MWK:
  NAD:
  NGN:
  NZD:
  OMR:
  ZMW:
  ZMK:
  PLN:
  XOF:
  QAR:
  RON:
  RSD:
  RWF:
  SAR:
  TMT:
  TND:
  TZS:
  UAH:
  UBC:
  UGX:
  XAF:
  VES:

profiles:
  low:
    max: 11
    default: 2
  high:
    min: 5
    default: 10
  base:
    default: 2
    max: 10
  highdefault:
    default: 4
    max: 13

hostProfiles:
  maverick: low
  THB: highdefault

