# default range of stake values

stakeValues:
  - 1
  - 2
  - 3
  - 5
  - 10
  - 20
  - 30
  - 50
  - 100
  - 200
  - 300
  - 500
  - 1000
  - 2000
  - 3000
  - 5000

defaultBet: 5 # index of stakeValues

ccyMultipliers:
  default:
    AED: 0.03
    ALL: 1
    AMD: 2
    AOA: 3
    ARS: 0.5
    AUD: 0.01
    ARX: 1.25
    AZN: 0.01
    BAM: 0.01
    BCH: 0.001
    BDT: 0.8
    BGN: 0.01
    BHD: 0.01
    BND: 0.01
    BOB: 0.05
    BRL: 0.05
  #  BTC: 0.01 # CRYPTO BTC. use UBC instead
    BWP: 0.05
    BYN: 0.02
    CAD: 0.01
    CDF: 10
    CHF: 0.01
    CLP: 8
    CNY: 0.07
    COP: 50
    CRC: 5
    CUP: 0.2
    CZK: 0.2
    DKK: 0.07
    DOP: 0.5
    DZD: 1.4
    EGP: 0.25
    ETB: 0.3
    ETH: 0.001
    EUR: 0.01
    GBP: 0.01
    GEL: 0.02
    GHS: 0.05
    GIP: 0.01
    GNF: 500
    GTQ: 0.05
    HKD: 0.05
    HNL: 0.1
    HRK: 0.05
    HTG: 0.5
    HUF: 4
    IDR: 100
    ILS: 0.03
    INR: 0.6
    IQD: 14
    IRR: 250
    IRT: 0.1
    ISK: 1
    JOD: 0.01
    JPY: 1.5
    KES: 1
    KGS: .8
    KRW: 13
    KWD: 0.01
    KHR: 40
    KZT: 4
    LBP: 25
    LKR: 1.5
    LSL: 0.1
    LTC: 0.001
    LYD: 0.03
    MAD: 0.1
  #  MBC: 0.04   # CRYPTO mBTC. MBC removed. use UBC instead
    MDL: 0.1
    MGA: 30
    MKD: 0.5
    MMK: 20
    MNT: 30
    MWK: 1
    MXN: 0.2
    MYR: 0.04
    MZN: 0.5
    NAD: 0.05
    NGN: 1
    NOK: 0.1
    NPR: 1.3
    NZD: 0.01
    OMR: 0.01
    PAB: 0.01
    PEN: 0.02
    PKR: 2
    PLN: 0.04
    PYG: 70
    QAR: 0.03
    RON: 0.04
    RSD: 1
    RUB: 0.6
    RWF: 5
    SAR: 0.03
    SEK: 0.1
    SLL: 100
    SOS: 5.5
    SSP: 1
    THB: 0.36
    TJS: .1
    TMT: 0.03
    TND: 0.02
    TRY: 0.18
    TZS: 10
    UAH: 0.1
    UBC: 1  # CRYPTO uBTC
    UGX: 50
    USD: 0.01
    UST: 0.01
    UYU: 0.4
    UZS: 100
    VES: 0.01
    VEX: 2000
    VND: 200
    XAF: 5
    XBT: 0.001
    XDR: 0.005
    XOF: 5
    ZAR: 0.14
    ZMK: 0.1
    ZMW: 0.15
  123:
    USD: 0.02


profiles:
  low:
    max: 11
    default: 2
  high:
    min: 5
    default: 10
  base:
    default: 2
    max: 10
  highdefault:
    default: 4
    max: 13

hostProfiles:
  maverick: low
  THB: highdefault

override:
  mvgEngineUnity1:
    credits:
      defaultBet: 10
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
  mvgEngineRoulette1:
    credits:
      defaultBet: 50
      minBet: 50
      maxBet: 200000
      stakeValues:
        - 50
        - 100
        - 200
        - 500
        - 1000
        - 2000
        - 5000
        - 10000
        - 50000
    TND:
      defaultBet: 0.1
      minBet: 0.1
      maxBet: 100
      stakeValues:
        - 0.1
        - 0.2
        - 0.4
        - 1
        - 2
        - 4
        - 10
        - 20
        - 100
  mvgEngineGodot4:
    credits:
      defaultBet: 6
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
  mvgEngineGodot5:
    credits:
      defaultBet: 10
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
  mvgEngineGodot6:
    credits:
      defaultBet: 10
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
  mvgEngineGodot7:
    credits:
      defaultBet: 10
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
  mvgEngineGodot8:
    credits:
      defaultBet: 10
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
  mvgEngineGodot8_94:
    credits:
      defaultBet: 10
      stakeValues:
        - 2
        - 4
        - 6
        - 10
        - 20
        - 40
        - 60
        - 100
        - 200
        - 400
