# default range of stake values

stakeValues:
  - 1
  - 2
  - 3
  - 5
  - 10
  - 20
  - 30
  - 50
  - 100
  - 200
  - 300
  - 500
  - 1000
  - 2000
  - 3000
  - 5000

defaultBet: 5 # index of stakeValues

ccyMultipliers:
  USD: 0.01
  CNY: 0.04
  EUR: 0.01
  GBP: 0.01
  VND: 100
  KRW: 10
  ZAR: 0.1
  JPY: 1
  THB: 0.2
  MYR: 0.02
  IDR: 100
  XBT: 0.001
  BTC: 0.001
  TRY: 0.05
  BRL: 0.04
  SEK: 0.01
  RUB: 0.5
  KZT: 3.5
  NOK: 0.01
  AMD: 5
  MMK: 10
  MXN: 0.2
  BOB: 0.05
  PYG: 50
  PEN: 0.02
  CLP: 5
  UYU: 0.4
  CAD: 0.01
  AED: 0.03
  ALL: 1
  AOA: 3
  ARS: 0.5
  AZN: 0.01
  BAM: 0.01
  BDT: 0.5
  BGN: 0.01
  BHD: 0.005
  BND: 0.01
  BWP: 0.05
  CDF: 10
  CHF: 0.01
  CRC: 5
  COP: 50
  CZK: 0.2
  DKK: 0.5
  DOP: 0.5
  EGP: 0.25
  GEL: 0.02
  GHS: 0.05
  GIP: 0.01
  GNF: 500
  GTQ: 0.05
  HKD: 0.05
  HRK: 0.05
  HTG: 0.5
  HUF: 5
  ILS: 0.03
  INR: 1
  IQD: 25
  IRR: 250
  ISK: 1
  JOD: 0.01
  KES: 1
  KWD: 0.005
  LBP: 25
  LSL: 0.1
  MAD: 0.1
  MBC: 0.01
  MKD: 0.5
  MWK: 1
  NAD: 0.05
  NGN: 1
  NZD: 0.1
  OMR: 0.005
  ZMW: 0.1
  ZMK: 0.1
  PLN: 0.3
  XOF: 5
  QAR: 0.03
  RON: 0.04
  RSD: 1
  RWF: 5
  SAR: 0.03
  TMT: 0.03
  TND: 0.02
  TZS: 50
  UAH: 0.25
  UBC: 1
  UGX: 50
  XAF: 5
  VES: 0.001
  ARX: 1.25
  VEX: 2000
  UST: 0.01
  ETH: 0.001
  BCH: 0.001
  LTC: 0.001
  BYN: 0.02
  UZS: 50
  MDL: 0.15
  LKR: 1.5
  MGA: 30
  TJS: .1
  KGS: .8

profiles:
  low:
    max: 11
    default: 2
  high:
    min: 5
    default: 10
  base:
    default: 2
    max: 10
  highdefault:
    default: 4
    max: 13

hostProfiles:
  maverick: low
  THB: highdefault

override:
  mah-jong:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  a-candy-girls-christmans:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  a-fairy-tale:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  a-hidden-forest:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  museum:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  asuka-x-samurai:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  bangkok-fighter:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  battlemech-mars:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  cloud9:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  cookoff-champion:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  crazy-easter-eggs:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  daytona:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  dragon-myst:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  drift:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  fruity-verse:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  goal:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  pearl-fisher:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  sky-jewels:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  sparta:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
  supa-crew:
    credits:
      defaultBet: 10
      stakeValues:
        - 3
        - 5
        - 10
        - 20
        - 30
        - 50
        - 100
        - 200
        - 300
        - 500
    UZS:
      defaultBet: 5000
      stakeValues:
        - 1500  
        - 2500  
        - 5000  
        - 10000 
        - 15000 
        - 25000 
        - 50000 
        - 100000  
        - 150000  
        - 250000
  valley-of-kings:
    UZS:
      defaultBet: 3000
      stakeValues:
        - 1000
        - 2000
        - 3000
        - 5000
        - 10000
        - 20000
        - 30000
        - 50000
        - 100000
        - 200000
