---
# Source: rgs-v2/templates/baseconfig.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: baseconfigs
  namespace: maverick
  labels:
    helm.sh/chart: rgs-v2-1.0.2
    app.kubernetes.io/name: rgs-v2
    app.kubernetes.io/instance: rgs-v2
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |
    # development mode
    devmode: true
    local: false

    # Log levels
    # debug, info, warn, error, fatal
    logging: debug
    environment: dev


    # mcrouter address
    mcrouter: mcrouter-memcached.default:11211

    # server configuration
    server:
      host: 0.0.0.0
      port: 3000
    
    sentryDsn: "https://9e9385a737394a4ead1619bc53bcce81@o422612.ingest.sentry.io/5351538"

    # dashur configuration
    dashurconf:
      storeurl: https://gnrc-api.dashur.io/v1/gnrc/maverick
      storeappid: VrCLq4UqYBf39rJt
      storeapppass: V6Kg9muzJxsz3nWFvJeyccU7

    defaultlanguage: en
    defaultplatform: html5

    demotokenprefix: demo-token-ezVVKaEv2nY7kP2gMCX7vfCH
    democurrency: USD
  gameConfig.yml: |
    - engineID: mvgEngineI
      games:
        - the-year-of-zhu
        - cat-thief
        - lantern-festival
        - crimson-masquerade
        - babaks-quest
        - astro-gems
        - jungle-saga
        - wukong-treasures
        - three-kingdom-shu
    - engineID: mvgEngineII
      games:
        - zodiac
        - street-racer
        - panda
        - three-kingdom-wu
        - candy-girls
        - bistro
    - engineID: mvgEngineIII
      games:
        - three-kingdom-wei
        - king-of-gamblers
        - a-million-lights
    - engineID: mvgEngineV
      games:
        - a-fairy-tale
        - a-candy-girls-christmas
    - engineID: mvgEngineVII
      games:
        - art-of-the-fist
        - battlemech
        - a-year-of-laoshu
        - candy-smash
    - engineID: mvgEngineIX
      games:
        - fruity-verse
        - a-hidden-forest
        - daytona
        - crazy-easter-eggs
    - engineID: mvgEngineX
      games:
        - seasons-winter
        - seasons-spring
        - seasons-summer
        - seasons-autumn
        - seasons
    - engineID: mvgEngineXII
      games:
        - cloud9
        - pearl-fisher
        - dragon-myst
    - engineID: mvgEngineXIII
      games:
        - sky-jewels
        - goal
        - cookoff-champion
        - drift
        - princess
    - engineID: mvgEngineXIV
      games:
        - valley-of-kings
        - bangkok-fighter
        - asuka-x-samurai
        - battlemech-mars
    - engineID: mvgEngineXI
      games:
        - mah-jong
    - engineID: mvgEngineXV
      games:
        - museum
    - engineID: mvgEngineXVI
      games:
        - sparta
    - engineID: mvgEngineXVII
      games:
        - book-of-living
    - engineID: mvgEngineXVIII
      games:
        - zodiac-elements
    - engineID: mvgEngineUnity1
      games:
        - supa-crew
    - engineID: mvgEngineGodot2
      games:
        - fox-tale
  gamification.yml: |
    a-candy-girls-christmas:
      function: Increment
      stages: 3
      spinsMin: 
      spinsMax: 
    a-fairy-tale:
      function: Increment
      stages: 3
      spinsMin: 
      spinsMax: 
    asuka-x-samurai:
      function: IncrementSpins
      stages: 5
      spinsMin: 50
      spinsMax: 70
    bangkok-fighter:
      function: IncrementSpins
      stages: 1
      spinsMin: 50
      spinsMax: 70
    battlemech:
      function: Increment
      stages: 3
      spinsMin: 
      spinsMax: 
    battlemech-mars:
      function: IncrementSpins
      stages: 5
      spinsMin: 50
      spinsMax: 70
    candy-smash:
      function: Increment
      stages: 3
      spinsMin: 
      spinsMax: 
    cookoff-champion:
      function: IncrementSpins
      stages: 3
      spinsMin: 50
      spinsMax: 70
    drift:
      function: IncrementSpins
      stages: 5
      spinsMin: 30
      spinsMax: 50
    goal:
      function: IncrementSpins
      stages: 3
      spinsMin: 50
      spinsMax: 70
    sky-jewels:
      function: IncrementSpins
      stages: 6
      spinsMin: 20
      spinsMax: 50
