---
# Source: rgs-v2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgs-v2
  namespace: maverick
  labels:
    helm.sh/chart: rgs-v2-1.0.2
    app.kubernetes.io/name: rgs-v2
    app.kubernetes.io/instance: rgs-v2
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rgs-v2
      app.kubernetes.io/instance: rgs-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rgs-v2
        app.kubernetes.io/instance: rgs-v2
    spec:
      imagePullSecrets:
        - name: harborcred2
      securityContext:
        {}
      containers:
        - name: rgs-v2
          securityContext:
            {}
          image: "harbor.inf01.activeops.io/maverick/mvg_rgs:v2.0.3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: rgs
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v2/rgs/healthcheck
              port: rgs
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v2/rgs/healthcheck
              port: rgs
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - mountPath: /internal/engine/engineConfigs/
              name: engineconfigs
            - mountPath: /config/
              name: baseconfigs
            - mountPath: /internal/parameterSelector/
              name: parameterconfig
            - mountPath: /internal/forceTool/forcedGameplays/
              name: forcetool
      volumes:
        - configMap:
            name: engineconfigs
          name: engineconfigs
        - configMap:
            name: baseconfigs
          name: baseconfigs
        - configMap:
            name: parameterconfig
          name: parameterconfig
        - configMap:
            name: forcetool
          name: forcetool
