---
# Source: rgs-v2/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rgs-v2
  namespace: maverick
  labels:
    helm.sh/chart: rgs-v2-1.0.2
    app.kubernetes.io/name: rgs-v2
    app.kubernetes.io/instance: rgs-v2
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rgs-v2
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
