---
# Source: rgs-v2/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rgs-v2
  namespace: maverick
  labels:
    helm.sh/chart: rgs-v2-1.0.2
    app.kubernetes.io/name: rgs-v2
    app.kubernetes.io/instance: rgs-v2
    app.kubernetes.io/managed-by: Helm
  annotations:
    field.cattle.io/ingressState: '{}'
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "Access-Control-Expose-Headers:
      ETag";'
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: Authorization, Content-Type, If-Match
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, OPTIONS, PUT
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/cors-max-age: "151200"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/http2-push-preload: "true"
spec:
  rules:
    - http:
        paths:
          - path: /v2
            backend:
              serviceName: rgs-v2
              servicePort: 3000
