---
# Source: rgs-v2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rgs-v2
  namespace: maverick
  labels:
    helm.sh/chart: rgs-v2-1.0.2
    app.kubernetes.io/name: rgs-v2
    app.kubernetes.io/instance: rgs-v2
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: rgs
      protocol: TCP
      name: rgs
  selector:
    app.kubernetes.io/name: rgs-v2
    app.kubernetes.io/instance: rgs-v2
