name: Build Dev

on: [push]
#  push:
#    branches:
#      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow Fetch
        run: git fetch --unshallow
      - name: Get Version Tag
        uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
        with:
          args: /github/workspace /exec /bin/sh /execargs "-c \"echo $GitVersion_MajorMinorPatch > /github/workspace/version.txt\""
      - run: |
          export BUILDVERSION=v$(cat /home/runner/work/rgs-core-v2/rgs-core-v2/version.txt)
          echo building rgs version $BUILDVERSION
          docker login harbor.inf01.activeops.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . -t harbor.inf01.activeops.io/maverick/mvg_rgs:$BUILDVERSION
          docker push harbor.inf01.activeops.io/maverick/mvg_rgs:$BUILDVERSION
      - name: Deploy Dev and Stg
        run: |
          export BUILDVERSION=v$(cat /home/runner/work/rgs-core-v2/rgs-core-v2/version.txt)
          cd deployment/helm
          sed -i "s/version.*/version: $BUILDVERSION/" values-dev.yaml
          sed -i "s/version.*/version: $BUILDVERSION/" values-stg.yaml
          sed -i "s/version.*/version: $BUILDVERSION/" values-prd.yaml
          git clone "https://${{ secrets.BUILDER_TOKEN }}@github.com/mvk-tech/mvk-deploy-dev.git"
          mkdir mvk-deploy-dev/dev
          mkdir mvk-deploy-dev/stg
          helm template rgs-v2/ -f values-dev.yaml --output-dir mvk-deploy-dev/dev
          helm template rgs-v2/ -f values-stg.yaml --output-dir mvk-deploy-dev/stg
          cd mvk-deploy-dev
          git checkout -b feature/deploy-dev-$BUILDVERSION
          git add dev/
          git commit -m "Deploy dev $BUILDVERSION"
          git push
          git checkout master
          git checkout -b feature/deploy-stg-$BUILDVERSION
          git add stg/
          git commit -m "Deploy stg $BUILDVERSION"
          git push
#
#
#      - name: Update Builder
#        run: |
#          git clone "https://${{ secrets.BUILDER_TOKEN }}@github.com/mvk-tech/rgs-builder.git"
#          cd rgs-builder/deployment/helm
#          echo updating dev build version
#          git checkout -b feature/deploy-dev-$BUILDVERSION
#          sed -i "" "s/version.*/version: $BUILDVERSION/" values-dev.yaml
#          git add values-dev.yaml
#          git commit -m "Update dev version to $BUILDVERSION"
#          git push
#          echo updating stg build version
#          git checkout master
#          sed -i "" "s/version.*/version: $BUILDVERSION/" values-stg.yaml
#          git checkout -b feature/deploy-stg-$BUILDVERSION
#          git add values-stg.yaml
#          git commit -m "Update stg version to $BUILDVERSION"
#          git push
#          echo updating prd build version
#          git checkout master
#          sed -i "" "s/version.*/version: $BUILDVERSION/" values-prd.yaml
#          git checkout -b feature/deploy-prd-$BUILDVERSION
#          git add values-prd.yaml
#          git commit -m "Update prd version to $BUILDVERSION"
#          git push
