name: DEV - Deploy RGS

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'charts/rgs-v2/Chart.yaml'
      - '**/.gitignore'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          make test
  build:
    runs-on: ubuntu-latest
    env:
      BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN  }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        id: tag
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ env.BUILDER_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - run: |
          echo building rgs version ${{ steps.tag.outputs.new_tag }}
          echo -n ${{ steps.tag.outputs.new_tag }} > version.txt          
          docker login harbor.elysiumstudios.se -u ${{ env.HARBOR_USERNAME }} -p ${{ env.HARBOR_PASSWORD }}
          docker build . -t harbor.elysiumstudios.se/elysium/mvg_rgs:${{ steps.tag.outputs.new_tag }}
          docker push harbor.elysiumstudios.se/elysium/mvg_rgs:${{ steps.tag.outputs.new_tag }}
      - name: Generate hashes
        run: |
          cd config
          sh genhashes.sh
          cat hashes.yml
          cd ..
      - uses: azure/setup-helm@v3
        with:
          version: "3.10.1"
        id: install
      - name: Update and push RGS helm chart
        run: |
          sed -i -e 's/appVersion:.*/appVersion: '${{ steps.tag.outputs.new_tag }}'/g' -e 's/^version:.*/version: '${{ steps.tag.outputs.new_tag }}'/' charts/rgs-v2/Chart.yaml
          git config --global user.email "workflow@elysiumstudios.se"
          git config --global user.name "Workflow"
          git add charts/rgs-v2/Chart.yaml 
          git commit -m "Deploy dev RGS ${{ steps.tag.outputs.new_tag }}"
          git push
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add --username=${{ env.HARBOR_USERNAME }} --password=${{ env.HARBOR_PASSWORD }} elysium-charts https://harbor.elysiumstudios.se/chartrepo/elysium/
          helm cm-push charts/rgs-v2/ elysium-charts

      - uses: actions/checkout@v2
        with:
          repository: Elysium-Studios/infrastructure
          token: ${{ env.BUILDER_TOKEN }}
          path: infrastructure
          
      - name: Update RGS release in flux repo
        run: |
          cd infrastructure/
          sed -i -e 's/version:.*/version: "${{ steps.tag.outputs.new_tag }}"/g' dev/apps-infra/deployments/rgs-v2/release.yaml
          git config --global user.email "workflow@elysiumstudios.se"
          git config --global user.name "RGS-V2 Workflow"
          git add dev/apps-infra/deployments/rgs-v2/release.yaml
          git commit -m "Deploy RGS-v2 ${{ steps.tag.outputs.new_tag }}"
          git push
