name: Build Dev

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow Fetch
        run: git fetch --unshallow
      - name: Get Version Tag
        uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
        with:
          args: /github/workspace /exec /bin/sh /execargs "-c \"echo $GitVersion_MajorMinorPatch > /github/workspace/version.txt\""
      - run: |
          export BUILDVERSION=v$(cat /home/runner/work/rgs-core-v2/rgs-core-v2/version.txt)
          echo building rgs version $BUILDVERSION
          docker login harbor.inf01.activeops.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . -t harbor.inf01.activeops.io/maverick/mvg_rgs:$BUILDVERSION
          docker push harbor.inf01.activeops.io/maverick/mvg_rgs:$BUILDVERSION
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.0.2'
        id: install
      - name: Deploy Dev and Stg
        run: |
          export BUILDVERSION=v$(cat /home/runner/work/rgs-core-v2/rgs-core-v2/version.txt)
          cd deployment/helm
          sed -i "s/version.*/version: $BUILDVERSION/" values-dev.yaml
          sed -i "s/version.*/version: $BUILDVERSION/" values-stg.yaml
          sed -i "s/version.*/version: $BUILDVERSION/" values-prd.yaml
          git clone "https://${{ secrets.BUILDER_TOKEN }}@github.com/mvk-tech/mvk-deploy-dev.git"
          helm template rgs-v2/ -f values-dev.yaml --output-dir mvk-deploy-dev/dev --name-template=rgs-v2
          helm template rgs-v2/ -f values-stg.yaml --output-dir mvk-deploy-dev/stg --name-template=rgs-v2
          cd mvk-deploy-dev
          git config user.email "miura@maverickslots.com"
          git config user.name "MEH Bot"
          git add dev/
          git commit -m "Deploy dev $BUILDVERSION"
          git push
          git checkout -b feature/deploy-stg-$BUILDVERSION
          git add stg/
          git commit -m "Deploy stg $BUILDVERSION"
          git push --set-upstream origin feature/deploy-stg-$BUILDVERSION
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(cat /home/runner/work/rgs-core-v2/rgs-core-v2/version.txt)
          release_name: Release v$(cat /home/runner/work/rgs-core-v2/rgs-core-v2/version.txt)
